### ISSUE TITLE
No wheel available for Windows and Python 3.5

### ISSUE THREAD

**Issue by rodrigc** [aleaxit/gmpy#111]
@casevh can you build a Windows Python 3.5 wheel (both 32-bit and 64-bit)
for gmpy2?

pypy only has up to Python 3.4.

I am trying to help with the CI for Twisted ( https://github.com/twisted/twisted ), and gmpy2
is a dependency.

Thanks.

**Comment by casevh** [comment]
Unfortunately, my old Windows build environment doesn't support Python 3.5. I am working on a new build environment but it isn't functional yet. There are wheels for Python 3.5 available at http://www.lfd.uci.edu/~gohlke/pythonlibs/

If you need them available for download at pypi, let me know and I'll see what I can do.

**Comment by rodrigc** [comment]
It would be helpful if you had Python 3.5 wheels available from PyPi because
that makes automation easier.

One thing you may want to consider is setting up a build environment with Appveyor,
and use that to publish your wheel.  I was skeptical about Appveyor before,
but have started using it, and am quite pleased.

**Comment by casevh** [comment]
The challenge is compiling versions of MPIR, MPFR, and MPC with various different Windows compilers. I am working on a new build environment that uses MSYS2 and the mingw compiler suite. One key advantage (for me) is that the mingw builds will automatically detect the CPU type and select the optimal code. I've had some successful builds and they have been much faster.

I need to release a new version in the next couple of weeks. I'll see if I can 3.5 wheels built.
