### ISSUE TITLE
Raising zero to a large power mismatch with Python long

### ISSUE THREAD

**Issue by agroce** [aleaxit/gmpy#114]
Python long gives 0 for (0 ** n) for any n, no matter how large.  mpz in gmpy2 raises a ValueError (outrageous exponent) if n is too large.  Can cause some issues if assuming complete drop-in replacement of mpz for Python long.

`>>> import gmpy2`
`>>> from gmpy2 import mpz`
`>>> mpz(0) ** (mpz(100) ** mpz(100))`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`ValueError: pow() outrageous exponent`
`>>> 0 ** (100 ** 100)`
`0L`

**Comment by agroce** [comment]
Can include a test case, but it seems pretty simple, and is either intentional or undesired behavior.

**Comment by agroce** [comment]
Discovered using random testing:  https://github.com/agroce/tstl/tree/master/examples/gmpy2

**Comment by casevh** [comment]
I've pushed a fix for this issue to the gmpy2-2.0.9 branch. I'll push a fix to the main development version soon.

Thanks for the report.

**Comment by agroce** [comment]
Thanks for fast fix -- I'll let you know if I see any other issues.  Only thing so far I believe Python long is in the wrong.

**Comment by agroce** [comment]
Same issue with 1 ** (large exponent) also exists, if the fix doesn't handle that, also

**Comment by casevh** [comment]
Updated fix tonight. :)

**Comment by agroce** [comment]
Great!  Took the tester much longer to find that one, since it had to generate a 1, which is harder than generating a 0 (since x-x == 0).

**Comment by casevh** [comment]
It will probably fail for -1, too.
