### ISSUE TITLE
segfault when working with RandomState objects in IPython

### ISSUE THREAD

**Issue by ces42** [aleaxit/gmpy#118]
In the standard Python shell I can do
```
>>> import gmpy2
>>> gmpy2.random_state()
<gmpy2.RandomState>
```

However in IPython (5.1.0):
```
In [1]: import gmpy2

In [2]: s = gmpy2.random_state()

In [3]: s
Out[3]: Segmentation fault (core dumped)
```
I also get a segfault when I try to use autocompletion on `s` after line 2.

I'm using Python 3.5.2 64-bit with gmpy2 2.0.8 compiled "by hand" on Ubuntu 16.10 64-bit with gmp 6.1.1 compiled "by hand" as well.

**Comment by casevh** [comment]
Can you try the gmpy2-2.0.9 branch?

https://github.com/aleaxit/gmpy/tree/gmpy2-2.0.9

It should be fixed there.

casevh

**Comment by ces42** [comment]
It works fine.
