### ISSUE TITLE
Add support for __int__

### ISSUE THREAD

**Issue by jdemeyer** [aleaxit/gmpy#124]
In Python, a conversion to an integer should use `__int__` if no conversion is known. If the `mpz` function does not know how to convert something to an `mpz`, it should try `PyNumber_Int`.

**Comment by casevh** [comment]
I'll take a look at this. I'll need to review the current numeric tower to see if PyNumber_Int or PyNumber_Index should be called.

**Comment by jdemeyer** [comment]
Since `mpz(2.5)` works and gives `2`, by analogy you should call `__int__`. The `__index__` method is for cases where something really is an integer in some form (say, a numpy or SageMath integer) and you want to convert to a Python `int`.

**Comment by casevh** [comment]
I have pushed a patch to the gmpy2-2.0.9 branch. Let me know if you test that branch. I'll also work on a patch for the main development branch.

**Comment by jdemeyer** [comment]
This indeed seems to work.
