### ISSUE TITLE
Document testing

### ISSUE THREAD

**Issue by jdemeyer** [aleaxit/gmpy#125]
The `gmpy2` sources contain directories `test`, `test2` and `test3`. As far as I can see, there is nothing documented about those tests. I assume that I need to execute `test/runtests.py` to run the tests? What about `test2` and `test3`?

**Comment by isuruf** [comment]
Also `test/runtests.py` fails on OSX for all python versions and on Linux for some python versions.

**Comment by casevh** [comment]
`test2` and `test3` are a subset of the tests from gmpy2 2.0.x. They will be removed eventually.

I am aware that `test/runtests.py` will report errors for some tests when run under Python 2.x. I'd like to get that fixed.

I just noticed that `posix64\mpz_aprcl.c` was compiled for all builds but it only supports 64-bit platforms where `long` is 64 bits. I am working on 32-bit Posix and Windows versions but that will be in the future.

I have no idea why it fails on OSX. Can you try again now that I've disabled `mpz_aprcl`? Please report the errors.

**Comment by isuruf** [comment]
On OSX failures are probably due to differences in the libm implementation. I don't have access to OSX directly, but here's a report from travis-ci.
https://travis-ci.org/isuruf/gmpy/builds/236247195

**Comment by isuruf** [comment]
You can click on each of the test cases to get the log. Here are the failing tests on OSX https://travis-ci.org/isuruf/gmpy/jobs/236247200#L200-L219

**Comment by casevh** [comment]
The Python 2.7 specific errors are due to changes in the return type for the ceil/round/trunc functions that were made for Python 3.

The OSX errors with the trig functions are due to libm errors.

I'll

**Comment by isuruf** [comment]
Here are some errors in windows.
https://ci.appveyor.com/project/isuruf/gmpy/build/1.0.7/job/owyi7qrjk59adnb3#L144

**Comment by isuruf** [comment]
The last error on windows is pretty serious,
```
assert int(i) + int(z) == i + z, (repr(i), repr(z))
AssertionError: ('-2147483648', 'mpz(0)')
```
This is probably due to converting to `long` after checking `mpz_fits_slong` with mpir. Note that `long` is 32 bits and `mpir_si` is 64 bits long.

**Comment by videlec** [comment]
> test2 and test3 are a subset of the tests from gmpy2 2.0.x. They will be removed eventually.

Could we do it now?

**Comment by casevh** [comment]
@videlec The obsolete tests have been removed.

**Comment by videlec** [comment]
Nice. Thanks. The issue could be closed then.

**Comment by casevh** [comment]
Completed.
