### ISSUE TITLE
inherit from Python's numeric ABCs

### ISSUE THREAD

**Issue by ces42** [aleaxit/gmpy#127]
Python has some abstract base classes (ABCs) designed for [implementing Numeric types](https://docs.python.org/3/library/numbers.html#module-numbers). As far as I know gmpy does not use this feature. Would it be possible to inherit `mpfr`, `mpz`, etc. from the respective ABCs?

**Comment by casevh** [comment]
Some of the gmpy codebase predates ABCs. I'm planning on dropping support for anything prior to 2.7 so it should be possible.

Can I ask what capabilities you are missing?

**Comment by ces42** [comment]
Basically it would be nice if `isinstance(gmpy2.mpfr(1), numbers.Real)` returned True. Although I have found that it isn't hard to produce this behaviour now:

    >>> mpfr = type(gmpy2.mpfr(0))
    >>> numbers.Real.register(mpfr)
    mpfr
    >>> isinstance(gmpy2.mpfr(1), numbers.Real)
    True

This probably means that it shouldn't be hard to get this behaviour "out of the box".

**Comment by casevh** [comment]
The branch for gmpy2-2.0.9 has been updated. I will update the master branch in a few days.

**Comment by ces42** [comment]
Great! Thanks.

**Comment by casevh** [comment]
I have updated the master branch. If you try the master branch, let me know if you encounter issues. I'm trying to finish some loose ends before I make the first alpha release.

**Comment by ces42** [comment]
seems to work
