### ISSUE TITLE
pack() issue

### ISSUE THREAD

**Issue by danielcrane** [aleaxit/gmpy#129]
When running the code:

```
import numpy as np
from gmpy2 import mpz, hamdist, pack

a = np.array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0])
ampz = pack(list(a),1)
```

as in [this stackexchange answer](http://stackoverflow.com/questions/32730202/fast-hamming-distance-computation-between-binary-numpy-arrays/32731304#32731304), I get the error:

```
TypeError: pack() requires list elements be positive integers < 2^n bits
```

I'm not sure if this is something that I'm doing incorrectly. If this is no longer possible, may I ask how one should convert a numpy array to a gmpy2 structure for use with hamdist?

Thanks.

**Comment by casevh** [comment]
The quick update is that the type of an element of list(a) is numpy.int64 which is not recognized by gmpy2.

Try list(map(int,a)) instead of list(a).

**Comment by danielcrane** [comment]
Thank you!
