### ISSUE TITLE
installation and detection of header files

### ISSUE THREAD

**Issue by videlec** [aleaxit/gmpy#136]
In #130 we discussed some possibility for installing gmpy2.h on the system. However the proposed solution (via the `headers` option in `setup.py`) is completely broken when one wants to compile something against `gmpy2`. There are several ways of installing Python modules and all of them should be supported
 - system installation (eg via `pip install`)
 - user installation (eg via `pip install --user`)
 - virtualenv
 - other?

A simple way to solve all this is to provide in `gmpy2` a function `get_include` similar to `numpy`

    >>> import numpy
    >>> numpy.get_include()
    '/usr/lib/python3.6/site-packages/numpy/core/include'

And I definitely think that installing `gmpy2.so`, `gmpy2.h` and `gmpy2.pxd` in the same repository (eg `/usr/include/python3.6/site-packages/`) is by far the simplest. Then the implementation of `get_include` would simply be

    def get_include():
        import os, gmpy2
        return os.path.dirname(gmpy2.__file__)

The advantage of providing a `get_include` function is that one can change the installation settings in later version without breaking user code.

**Comment by videlec** [comment]
Solved with #130 (except that the PR does not provide the `get_include`)

**Comment by jdemeyer** [comment]
> except that the PR does not provide the get_include

There is no reason for that when using Cython. So I consider this issue 100% fixed, as least for Cython users.
