### ISSUE TITLE
type checkers in the public C-API

### ISSUE THREAD

**Issue by videlec** [aleaxit/gmpy#139]
It would be convenient to have the following macros available from the public C-API
- `MPZ_Check` (now in `gmpy2_mpz.h`)
- `MPQ_Check` (now in `gmpy2_mpq.h`)
- `MPFR_Check` (now in `gmpy2_mpfr.h`)
- `MPC_Check` (now in `gmpy2_mpc.h`)

**Comment by casevh** [comment]
I will try to add those tonight.

**Comment by videlec** [comment]
Would be fantastic!

**Comment by casevh** [comment]
After a review of the code, the macros are already available. See line ~500 in gmpy2.h.

Assume that we are just looking at MPZ_Check. The macro defined in gmpy2_mpz.h can directly reference the type object MPZ_Type. However, MPZ_Type is not directly accessible to an extension module and must be referenced via the GMPy_C_API array.

At least, that's what I think it does. Are you getting an error?

**Comment by vinklein** [comment]
I just made a test, by adding MPZ_Check in gmpy2.pxd and calling it in a Cython pyx file, it works.
