### ISSUE TITLE
mpq floor division

### ISSUE THREAD

**Issue by ces42** [aleaxit/gmpy#156]
floor division on `mpq`s just seems to return the numerator:

    Python 3.6.1 (default, Mar 22 2017, 06:17:05) 
    [GCC 6.3.0 20170321] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from gmpy2 import mpq
    >>> mpq(355, 113) // 2
    mpz(355)

is this intended?

**Comment by casevh** [comment]
Not intended. I'll try to look at it this weekend.

**Comment by videlec** [comment]
Could the issue be closed?

**Comment by casevh** [comment]
Fix will be available in 2.1 series. The first release should be out soon.

**Comment by ces42** [comment]
Thanks!
