### ISSUE TITLE
activate Travis CI

### ISSUE THREAD

**Issue by videlec** [aleaxit/gmpy#162]
It seems that Travis CI is not activated on gmpy2 main repo (ie nothing at https://travis-ci.org/aleaxit/gmpy to be compared with https://travis-ci.org/videlec/gmpy). This would allow automatic testing on pull request.

**Comment by videlec** [comment]
ping?

**Comment by videlec** [comment]
ping?

**Comment by casevh** [comment]
I will try to contact Alex again. He owns the main repository.

**Comment by skirpichev** [comment]
I think the Github Actions now is used for CI, right, @casevh?  Then .travis.yml can be just removed.
