### ISSUE TITLE
PyPI sources do not contain gmpy2/gmpy2.h symlink

### ISSUE THREAD

**Issue by jdemeyer** [aleaxit/gmpy#195]
The file `gmpy2/gmpy2.h` is not shipped in the source tarball. Because of this, the `gmpy2.h` header file is not installed when installing from the source tarball.

CC @pkittenis

Note: this was originally reported as #189 but without mentioning that this was sdist-specific.

**Comment by pkittenis** [comment]
The latest pre-release version (2.1.0a2), is [not the latest](https://github.com/aleaxit/gmpy/commit/15f9e8a23f3a4db8fd8dfb93d37478cbe8f4ae28).

Current master sdist does contain gmpy2.h:

```
gmpy$ python setup.py sdist
$ tar -tvf dist/gmpy2-2.1.0a3.dev0.tar.gz  | grep gmpy2.h
-rw-rw-r-- xx/xx    2421 2018-01-22 14:53 gmpy2-2.1.0a3.dev0/src/gmpy2_hash.h
-rw-rw-r-- xx/xx    6636 2018-01-22 14:53 gmpy2-2.1.0a3.dev0/src/gmpy2_hash.c
-rw-rw-r-- xx/xx   20719 2018-06-06 14:47 gmpy2-2.1.0a3.dev0/src/gmpy2.h
```

No idea how the latest pypi release was built, but this does not look an issue with current master version of setup.

**Comment by jdemeyer** [comment]
Sorry, I meant `gmpy2/gmpy2.h`

**Comment by pkittenis** [comment]
Source distributions do not read package data and need `MANIFEST.in` (ugh). See PR.
