### ISSUE TITLE
Libmpfr4 no longer available on Ubuntu 18.04

### ISSUE THREAD

**Issue by ChenyuLInx** [aleaxit/gmpy#203]
I tried to import gmpy2 in python2.7 on ubuntu 18.04. But kept getting this error:

> ImportError: libmpfr.so.4: cannot open shared object file: No such file or directory

**Comment by ChenyuLInx** [comment]
Seems like the source version is fine, just the anaconda pip version does not work

**Comment by ahmadnurhadirmw** [comment]
sudo apt install libmpfr-dev

**Comment by casevh** [comment]
This is an issue with the anaconda version and missing libmpfr (and possibly missing libmpc) files. I would just do "sudo apt install libmpc-dev" since that will also install libmpfr.
