### ISSUE TITLE
2.1.0a3 missing files in source release

### ISSUE THREAD

**Issue by vinklein** [aleaxit/gmpy#204]
Hi case, 

Thanks for the source release  (#198).
Unfortunately pplpy doesnt compile with the package on pypi [gmpy2-2.1.0a3.tar.gz](https://files.pythonhosted.org/packages/46/72/3d7b689c618cdbc5353231d0cac82cb49c286f587c333e471607e4fb9328/gmpy2-2.1.0a3.tar.gz
), but it does with the current trunk.  Pypi's package seems to miss two files [gmpy2/gmpy2.pxd](https://github.com/aleaxit/gmpy/blob/master/gmpy2/gmpy2.pxd) and [gmpy/__init__.pxd](https://github.com/aleaxit/gmpy/blob/master/gmpy2/__init__.pxd).

**Comment by pkittenis** [comment]
Those files seem to be missing from [MANIFEST.in](https://github.com/aleaxit/gmpy/blob/master/MANIFEST.in) which is the only way non-python files can be included into a source distribution.

**Comment by vinklein** [comment]
@pkittenis Thanks for the tip.

**Comment by vinklein** [comment]
@casevh 
Hi Case,
When do you plan to do another cython compatible source release  ?
May i help you in some way in order to speed up the process ?

**Comment by casevh** [comment]
I have tagged the 2.1.0a4 release and the tar file that I plan to distribute can be downloaded from Github at https://github.com/aleaxit/gmpy/releases/tag/gmpy2-2.1a4

I will publish it on PyPi tomorrow.

**Comment by vinklein** [comment]
Thanks !
I will do some tests today.

**Comment by casevh** [comment]
I've published the latest source on PyPi.
