### ISSUE TITLE
qdiv() doesn't return mpz() in some situations

### ISSUE THREAD

**Issue by casevh** [aleaxit/gmpy#207]
qdiv(8,2) and qdiv(4.1) should both return mpz(4).

Reported on StackOverflow.

**Comment by skirpichev** [comment]
@casevh, probably this was fixed by https://github.com/aleaxit/gmpy/commit/b6a8ea6188352139a7d28342ee4630e14c65b7e5

btw, you can [close issues with commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/).

**Comment by casevh** [comment]
Thanks for the hint. The bug has been fixed.
