### ISSUE TITLE
using gmp Logical and Bit Manipulation Functions

### ISSUE THREAD

**Issue by akhilharihar** [aleaxit/gmpy#208]
The gmp Logical and Bit Manipulation Functions(mpz_and , mpz_ior etc.,) are not documented bit I could find their implementation in this library. Can anyone help me out on how to use those functions?

**Comment by casevh** [comment]
The `mpz_and()`, `mpz_ior()`, and mpz_xor()` functions are accessed via the standard Python and (`&`), or (`|`), and exclusive-or (`^`) operators.

`>>> import gmpy2
>>> gmpy2.mpz(12) & gmpy2.mpz(34)
mpz(0)
>>> gmpy2.mpz(12) | gmpy2.mpz(34)
mpz(46)
>>> gmpy2.mpz(12) ^ gmpy2.mpz(34)
mpz(46)
>>> 
`

The `mpz` type is designed to mimic the standard Python integer type. It is an immutable type so the in-place operators always return a new object.

`>>> a=gmpy2.mpz(12)
>>> b=a
>>> a |= gmpy2.mpz(34)
>>> a
mpz(46)
>>> b
mpz(12)
>>> 
`
gmpy2 defines a mutable integer type called `xmpz` that supports in-place modification.

`>>> a=gmpy2.xmpz(12)
>>> b=a
>>> a |= gmpy2.xmpz(34)
>>> a
xmpz(46)
>>> b
xmpz(46)
>>> 
`

The `xmpz` type can be considered as a list of bits. You can iterate over all the bits, the bits that are set, or the bits that are clear.

`>>> list(gmpy2.xmpz(12).iter_bits())
[False, False, True, True]
>>> list(gmpy2.xmpz(12).iter_set())
[2, 3]
>>> list(gmpy2.xmpz(12).iter_clear())
[0, 1]
>>> 
`
You can also use the standard slice notation to access individual bits.

`>>> a=gmpy2.xmpz(12)
>>> a[2]
1
>>> a[2]=0
>>> a
xmpz(8)
>>> a[2]=1
>>> a
xmpz(12)
`

Or even arbitrary sequences of bits.

`>>> a=gmpy2.xmpz(23456)
>>> a[0::2] # all even bits
mpz(208)
>>> a[1::2] # all odd bits
mpz(60)
>>>
>>> b=gmpy2.xmpz(0)
>>> b[1:99:2] = 60  # 99 is just a value greater than the number of bits to set
>>> b[0:99:2] = 208
>>> b
xmpz(23456)
>>> 
`
Let me know if you have a specific problem to solve.

**Comment by akhilharihar** [comment]
@casevh thanks for the info.
