### ISSUE TITLE
Improve project description and add link to readthedocs

### ISSUE THREAD

**Issue by slel** [aleaxit/gmpy#215]
The main page for this repo on GitHub,

> https://github.com/aleaxit/gmpy

has this description

> Automatically exported from code.google.com/p/gmpy

which could be replaced by a description of the project such as

> Python module for multiple-precision arithmetic with GMP, MPIR, MPFR, MPC

or the same description as on PyPI:

> GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x

In addition, GitHub lets the project owner set a url for the project,
and it would be nice if this could be filled with the readthedocs url:

> https://gmpy2.readthedocs.io/en/latest/

It was also suggested at https://github.com/aleaxit/gmpy/issues/146#issuecomment-314781226
to link to readthedocs from the PyPI page.

Finally, the readthedocs page could have links to the GitHub repo
and to the PyPI page.

**Comment by aleaxit** [comment]
Done for this github repo -- Case, can you please do the changes to readthedocs and pypi?
