### ISSUE TITLE
Several bugs in gmpy2_mpz_bitops functions

### ISSUE THREAD

**Issue by vinklein** [aleaxit/gmpy#222]
Error cases of gmpy2.bit_scan0 provoque core dump:
```
>>> import gmpy2
>>> from gmpy2 import mpz
>>> gmpy2.bit_scan0(8.4)
Segmentation fault (core dumped)

>>> gmpy2.bit_scan0()
Segmentation fault (core dumped)

>>> gmpy2.bit_scan0(mpz(7), 2, 5)
Segmentation fault (core dumped)
```

**Comment by vinklein** [comment]
Same bug with `gmpy2.scan1`.

**Comment by casevh** [comment]
I think the line

    Py_DECREF((PyObject*)tempx);

in GMPy_MPZ_bit_scan0_function and GMPy_MPZ_bit_scan1_function needs to be
Py_XDECREF(..)

Can't test until later.

**Comment by vinklein** [comment]
Yes your fix works. I will include it in my next PR.

**Comment by vinklein** [comment]
GMPy_MPZ_bit_flip_function always return an error.

**Comment by casevh** [comment]
Thank you!
