### ISSUE TITLE
xmpz iand operator return wrong result

### ISSUE THREAD

**Issue by vinklein** [aleaxit/gmpy#224]
```
>>> x = xmpz(2)
>>> x &= xmpz(1); x
xmpz(0)
```

**Comment by casevh** [comment]
That looks correct to me. 2 is ...00010 in binary and 1 is ...00001 in
binary. A bitwise logical and should be all zeros.

With Python ints, I also get 0.

>>> 2 & 1
0

**Comment by vinklein** [comment]
Yes of course my bad.
