### ISSUE TITLE
2.1.0b1 test failures on 32-bit arches

### ISSUE THREAD

**Issue by jamesjer** [aleaxit/gmpy#244]
On 32-bit x86 and 32-bit ARM, these tests fail:

**********************************************************************
File "test/test_gmpy2_mpfr_misc.txt", line 36, in test_gmpy2_mpfr_misc.txt
Failed example:
    gmpy2.get_emin_min()
Differences (ndiff with -expected +actual):
    - -4611686018427387903
    + -1073741823
**********************************************************************
File "test/test_gmpy2_mpfr_misc.txt", line 38, in test_gmpy2_mpfr_misc.txt
Failed example:
    gmpy2.get_emax_max()
Differences (ndiff with -expected +actual):
    - 4611686018427387903
    + 1073741823
**********************************************************************
File "test/test_gmpy2_mpfr_misc.txt", line 154, in test_gmpy2_mpfr_misc.txt
Failed example:
    r.__sizeof__() # doctest: +SKIP_IN_DEBUG_MODE
Differences (ndiff with -expected +actual):
    - 72
    + 40
**********************************************************************
File "test/test_gmpy2_mpq_misc.txt", line 98, in test_gmpy2_mpq_misc.txt
Failed example:
    q.__sizeof__() # doctest: +SKIP_IN_DEBUG_MODE
Differences (ndiff with -expected +actual):
    - 88
    + 56
**********************************************************************
File "test/test_gmpy2_mpq_misc.txt", line 100, in test_gmpy2_mpq_misc.txt
Failed example:
    mpq(0/5).__sizeof__() # doctest: +SKIP_IN_DEBUG_MODE
Differences (ndiff with -expected +actual):
    - 88
    + 52
**********************************************************************
File "test/test_gmpy2_xmpz_misc.txt", line 123, in test_gmpy2_xmpz_misc.txt
Failed example:
    x.__sizeof__() # doctest: +SKIP_IN_DEBUG_MODE
Differences (ndiff with -expected +actual):
    - 40
    + 24
**********************************************************************

**Comment by casevh** [comment]
The errors with the sizeof() tests are expected. I will probably just remove them since they rely on internal implementation details.

I will look at the other two issues.

**Comment by casevh** [comment]
The tests have been updated to remove the platform specific tests. Test pass on 32-bit Linux but I tried ARM.

**Comment by jamesjer** [comment]
I can confirm that the tests now pass on all architectures.  Thank you!

**Comment by casevh** [comment]
Fix pushed in 2.1.0b3.
