### ISSUE TITLE
Speed regression in 2.1.0b1

### ISSUE THREAD

**Issue by skirpichev** [aleaxit/gmpy#246]
Mentioned [here](https://github.com/aleaxit/gmpy/pull/245#issuecomment-496143256) and [here](https://github.com/aleaxit/gmpy/pull/217#issuecomment-497352845).

I was able to bisect the problem to single commit cfd8ec12 in #217.  This is the diofant build on top of the gmpy master: https://travis-ci.org/diofant/diofant/builds/546084979.  And this is the build (successful) on top of the branch [fix-speed-regr](https://github.com/skirpichev/gmpy/tree/fix-speed-regr): https://travis-ci.org/diofant/diofant/builds/546086719.  (The branch [reverts](https://github.com/skirpichev/gmpy/commit/134309628d56b1d1e3d9b698d27018c37e0acfa4) part of the mention commit.)

**Comment by vinklein** [comment]
Hello @skirpichev. IS_INTEGER macro is used in a lot of place in gmpy2 code. Can you tell what calls are hurting diofant speed ?

**Comment by skirpichev** [comment]
> Can you tell what calls are hurting diofant speed?

No, I can't, yet.

**Comment by casevh** [comment]
I've test the performance of basic mpz operations including types that include __mpz__ and those that don't and I don't see an obvious issue. But it might be related to issue #243. The code that creates an mpfr objects is supposed to have two different behaviors: if the precision is 0, then the result have the same precision as the context (and rounding may occur); if the precision is 1, then the result will be converted without rounding. That latter option avoids rounding but can cause high-precision intermediate operations. I think the default may have changed to 1 instead of 0. I actually prefer the lossless conversion since it avoid double rounding but can cause slowdowns.

I will look at issue #243 this weekend.

Do you know if mpfr objects are used and could they be the source of the slowdown?

**Comment by skirpichev** [comment]
> Do you know if mpfr objects are used

I doubt so.  Diofant uses mpmath for multiple-precision floating point computations.  AFAIR, mpmath doesn't uses gmpy2's mpfr internally.

**Comment by casevh** [comment]
I ran the test suite (py.test --pyargs diofant) on my test VM. With the a4 release, the running time was 3172 seconds. Withe the b1 release, the running time was 3423 seconds. I will repeat the tests a few time to check if the difference is repeatable.

**Comment by casevh** [comment]
I ran the test suite again and the times were consistent. I compared the times for the slowest tests. `test_wester::W24` was 130 seconds slower and `test_heurisch` was 80 seconds slower. The slowdown in those two tests account for around 2/3 of the total delay. Can you think of anything they have in common?

**Comment by skirpichev** [comment]
> Withe the b1 release, the running time was 3423 seconds.

b1 release is broken, there should be some test failures, so I'm not sure timings have sense.  Have you seen these?  https://github.com/aleaxit/gmpy/pull/245 fix that.

> I compared the times for the slowest tests.

Some slow tests, e.g. test_pmint_WrightOmega() several times more slower now and use several times more memory.  Did you notice that?  [This fix](https://github.com/diofant/diofant/pull/856/commits/1005052e60cf14127e611c47f3a9c63d44936656) make memory problem and running time less severe, but still - this test almost 2x slower in the current gmpy master than on alpha4.

**Comment by casevh** [comment]
I was actually using using the current master which has the fix but I haven't updated the version string.

I have another idea that I'll look at this weekend.

**Comment by skirpichev** [comment]
test_dup_isolate_complex_roots_sqf_2() - an another example where regression is present.  On a4 it runs in 18s on my notebook, while on the gmpy master it hits timeout (40s).

PS: Sorry, https://github.com/diofant/diofant/pull/856/commits/1005052e60cf14127e611c47f3a9c63d44936656 seems to be effective wrt to speed and memory only for b1.  On the master it has no effect and there are still ~2x slowdown vs a4 on the test_pmint_WrightOmega().

**Comment by casevh** [comment]
A quick update... I am investigating possible slowdowns caused by a few classes that define a custom __getattr__ function. That function will be called if an attribute doesn't already exist. I think the calls from C to Python is causing the delay.

Unfortunately, I don't know how this could be fixed. :(

**Comment by skirpichev** [comment]
Which attribute?

**Comment by skirpichev** [comment]
Hmm, I doubt it's the case.  No classes involved redefine getattr with ``__getattribute__`` or do something else nasty.  Especially, this shouldn't affect test_dup_isolate_complex_roots_sqf_2().

**Comment by casevh** [comment]
The change that triggered the slowdown implements automatic conversion between gmpy2 types and arbitrary types. `mpz + arbitrary` causes a lookup for `__mpz__` attribute on the arbitrary type to handle the conversion to mpz. If the attribute lookup fails, then `__getattr__` is called. I found three locations in the diofant codebase that define `__getattr__`. I made a change to `--getattr__` used in the Singleton class to start with a specific test for `__mpz__` and return immediately. There was a small improvement but I need to rerun to verify it really made a difference. I haven't looked at any other dependencies.

I'll keep looking....

**Comment by skirpichev** [comment]
> I made a change to --getattr__ used in the Singleton class to start with a specific test for __mpz__ and return immediately. There was a small improvement

I doubt.   It shouldn't affect  test_dup_isolate_complex_roots_sqf_2().  More simple version:
```python
from diofant import ZZ
R = ZZ.poly_ring("x")
x, = R.gens
f = x**20 - 15*x**17 - 21*x**3 + 11

res = R.dup_isolate_complex_roots_sqf(f)
```

This snippet took ~5s on a4 and now it runs ~25s on the master.  The last line take most time and it doesn't use singleton module.

Are you sure there is no unexpected slowdowns just for mpz/mpq + int?

**Comment by skirpichev** [comment]
Indeed...

```
(dev) sk@note:~/src/diofant $ pip install --pre -U gmpy2==2.1.0a4
...
Successfully installed gmpy2-2.1.0a4
$ jupyter console --kernel=dev
In [1]: a = QQ(1111111111111111111111111111111111111, 777777777777777777777777777777777777777777777777777)

In [2]: b = int(1213121212121212121212121212122332453434534534534535435543543534)

In [3]: %timeit a*b
2.44 µs ± 5.08 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
...
(dev) sk@note:~/src/diofant $ pip install --pre -U git+https://github.com/aleaxit/gmpy.git
...
Successfully installed gmpy2-2.1.0b1
(dev) sk@note:~/src/diofant $ jupyter console --kernel=dev
...
In [3]: %timeit a*b
5.91 µs ± 10.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
...
```
