### ISSUE TITLE
Support MPIR as a GMP alternative on Unix

### ISSUE THREAD

**Issue by skirpichev** [aleaxit/gmpy#248]
Currently, --mpir switch just doesn't work (yet, it's documented!):
```
(dev) sk@note:~/src/gmpy $ python setup.py build_ext --mpir
running build_ext
building 'gmpy2.gmpy2' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./src -I/home/sk/venv/dev/include -I/usr/include/python3.7m -c src/gmpy2.c -o build/temp.linux-x86_64-3.7/src/gmpy2.o -DSHARED=1 -DMPIR=1
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/gmpy2
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.7/src/gmpy2.o -lmpc -lmpfr -lgmp -o build/lib.linux-x86_64-3.7/gmpy2/gmpy2.cpython-37m-x86_64-linux-gnu.so
(dev) sk@note:~/src/gmpy $ ldd build/lib.linux-x86_64-3.7/gmpy2/gmpy2.cpython-37m-x86_64-linux-gnu.so 
	linux-vdso.so.1 (0x00007fffc61ab000)
	libmpc.so.3 => /usr/lib/x86_64-linux-gnu/libmpc.so.3 (0x00007f2a96564000)
	libmpfr.so.6 => /usr/lib/x86_64-linux-gnu/libmpfr.so.6 (0x00007f2a964e2000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f2a9645f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2a9643e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2a9627d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2a960fa000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2a96837000)
```

**Comment by casevh** [comment]
Summary: I was planning to remove that option.

It has been a while since I used MPIR (other than on Windows). It used to be possible to build gmpy2 without MPFR or MPC. --mpir would import mpir.h and --gmp would import gmp.h. It was useful compare performance between GMP and MPIR.

MPFR and MPC are now requirements. I could easily be wrong, but I think MPFR assumes MPIR was compiled in `gmp-compat` mode and so importing gmp.h would be the right think to do. 

And on Windows, I am trying to migrate to an msys2/mingw build. The primary advantage is auto-recognition of the CPU architecture. I saw a 30% improvement between Visual Studio and mingw builds. And the mingw builds just use GMP.

Is there a specific use case?

**Comment by skirpichev** [comment]
> Is there a specific use case?

AFAIK, sagemath now uses mpir as a default backend for integer/rational arithmetics.  I was interested in comparing performance gmp vs mpir on the diofant too.

**Comment by vinklein** [comment]
> AFAIK, sagemath now uses mpir as a default backend
Yes but to be a little more accurate if the user has gmp installed on his system and not mpir, gmp will be used by sagemath.
And beside that, sagemath's `configure` allow the user to choose if he want to install gmp or mpir.
To sum up that mean that sagemath will be impacted if gmpy2 drop mpir support. 
The two possibles adaptation being removing gmpy2 as a standard package from sagemath or making gmp choice mandatory (I am not sure if the sagemath community will agree with that or not).

**Comment by isuruf** [comment]
sagemath compiles MPIR with `--enable-gmpcompat` and therefore this option is not necessary for sagemath. (sagemath's `configure` also looks for a MPIR in system with that option enabled)

Only issue is when a user compiles MPIR without that option.

**Comment by casevh** [comment]
Closing since gmpy2 assumes --enable-gmpcompat when using MPIR.
