### ISSUE TITLE
Comparison of mpq with custom rational object is broken

### ISSUE THREAD

**Issue by vinklein** [aleaxit/gmpy#251]
```
python3.7
Python 3.7.4 (default, Jul  9 2019, 03:52:42) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gmpy2 import mpz, mpq
>>> class Q:
...     def __mpq__(self): return mpq(3,2)
... 
>>> q = Q()
>>> mpq(3, 2) * q
mpq(9,4)
>>> mpq(3, 2) == q
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot convert object to mpq
>>> from gmpy2 import cmp
>>> cmp(mpq(3,2), q)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot convert object to mpq
```
Bug first found in sagemath (see: https://trac.sagemath.org/ticket/28394).

**Comment by vinklein** [comment]
We have bugs too with {{{cmp}}} between {{{mpz}}} and custom rational:

{{{
>>> cmp(mpz(1), q)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'mpz' is not defined
>>> from gmpy2 import mpz
>>> cmp(mpz(1), q)
twoTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot convert object to mpq
>>> mpz(1) == q
False
>>> cmp(q, mpz(1))
oneTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot convert object to mpq
>>> q == 1
False
}}}

**Comment by vinklein** [comment]
Ok thanks.

**Comment by casevh** [comment]
I have release 2.1.0b4. It should have all the issues resolved.

**Comment by slel** [comment]
Close this issue?

**Comment by skirpichev** [comment]
@casevh, probably you could close this.
