### ISSUE TITLE
Tests failing with Python 3.8

### ISSUE THREAD

**Issue by martingkelly** [aleaxit/gmpy#259]
Hi,

I'm the Debian maintainer for this package. Recently, a bug was filed indicating that the tests are failing with Python 3.8. This should be reproduceable with the following command:

python3 test/runtests.py

Debian is using the PyPi 2.1.0b3 release.

This is the link to the associated Debian bug report, including output for the failing tests:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950205

**Comment by casevh** [comment]
I have release b4 which should resolve this.

**Comment by martingkelly** [comment]
Awesome, I will package that as soon as I can.

**Comment by slel** [comment]
Can this issue be closed?

**Comment by skirpichev** [comment]
@casevh, probably you can close this.
