### ISSUE TITLE
64-bit Python 3.8 - GMPY2 v.2.0.8 - Error during pow operation

### ISSUE THREAD

**Issue by giuseppefilippone** [aleaxit/gmpy#261]
Hi,

I'm using 64-bit Python 3.8 with GMPY2 v.2.0.8. I noticed a strange error during pow operation:
```
>>> from gmpy2 import mpq
>>> mpq(465) ** 6
mpq(10109221616390625,1)
>>> mpq(465) ** mpq(6)
mpfr('10109221616390624.0')
```
I don't understand why there is this error.

**Comment by casevh** [comment]
The internal code checks if the exponent is a known integer type. If it isn't, it just returns a floating point result. 

I don't know if it makes sense to check if the exponent can be exactly converted to an integer. Do you have a specific use case?

**Comment by giuseppefilippone** [comment]
I was working with my cryptography library.  I noticed a strange error during the calculation.  I looked for the problem and I found this error.  If you try to do the same with other numbers this phenomenon does not appear:
```
>>> from gmpy2 import mpq
>>> mpq(12) ** 6
mpq(2985984,1)
>>> mpq(12) ** mpq(6)
mpfr('2985984.0')
```
The same result is obtained, even if the class changes from mpq to mpfr.  It is strange that the result changes based on the power base.

PS: In the previous case, `mpq (465) ** mpq(6)` returns an incorrect result. I am not interested in the transition from mpq to mpfr.  I am concerned that 465 ^ 6 returns an incorrect result which is exactly one unit minus the correct result (check the result numbers).  It is as if 10 ^ 3 returns 999 instead of 1000.

**Comment by isuruf** [comment]
It depends on the `precision` in the current context. This is similar to the following using python types.
```python
>>> 465**6.0
1.0109221616390624e+16
>>> 465**6
10109221616390625
```

**Comment by giuseppefilippone** [comment]
I thought the gmpy2 library didn't suffer from this problem.

**Comment by casevh** [comment]
gmpy2's default precision for floating point is 53 bits. 465**6 requires 54 bits. Increasing the precision will give you the answer you expect.

```
>>> gmpy2.get_context().precision=100
>>> gmpy2.mpz(465)**gmpy2.mpq(6)
mpfr('10109221616390625.0',100)
```

**Comment by giuseppefilippone** [comment]
So that's the problem... Ok, thanks!
