### ISSUE TITLE
Is it possible to check what GMP version is linked?

### ISSUE THREAD

**Issue by sethtroisi** [aleaxit/gmpy#264]
(big fan, love this package)

I'm trying to benchmark some prime testing code. gmp improved `mpz_probab_prime_p` in 6.2.0 release. Is there a way of determining the gmp version is being used when using gmpy? something like `gmpy2.__version__` but for gmp version?

Thanks

**Comment by casevh** [comment]
The three functions `gmpy2.mp_version()`, `gmpy2.mpfr_version()`, and `gmpy2.mpc_version()` should do it.

**Comment by sethtroisi** [comment]
Thanks!
