### ISSUE TITLE
Representing a large number in scientific form?

### ISSUE THREAD

**Issue by deostroll** [aleaxit/gmpy#272]
I took the advice from [here](https://stackoverflow.com/a/1529607/145682)

```
>>> import gmpy2
>>> k = gmpy2.mpz(17) ** 2 ** 3
>>> print(k)
6975757441
>>> gmpy2.digits(k, 10)
'6975757441'
>>> gmpy2.digits(k, 10, 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: digits() requires 'int' argument for base
>>> l = gmpy2.mpfr(k)
>>> gmpy2.digits(l, 10, 3)
('698', 10, 53)
>>> gmpy2.digits(l, 10, 2)
('70', 10, 53)
>>> gmpy2.digits(l, 10, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: digits must be 0 or >= 2
>>> gmpy2.digits(l, 10, 5)
('69758', 10, 53)
```
I don't quite understand the output of `gmpy2.digits(l, 10, 3)` above. I was expecting `6.98e9`. Or am I to read it as `0.698e10`?

**Comment by casevh** [comment]
Note: there have been some changes between the original `gmpy` and the current `gmpy2`.

It should be read as `0.698e10`.

You may want to use `str.format()` support. The options for an `mpfr` type can be found by `help(gmpy2.mpfr.__format__)`. `str.format()` calls the `__format__` method for the various types of its arguments.

    >>> l.__format__('0.3e')
    '6.976e+09'
    >>> "The number to 3 digits of precision is {0:0.3e}.".format(l)
    'The number to 3 digits of precision is 6.976e+09.'

The format strings are defined by MPFR and are slightly different than Python's format string. See section 5.9.2 at https://www.mpfr.org/mpfr-current/mpfr.html#Formatted-Output-Functions for more details.

Does this help?
