### ISSUE TITLE
Add wheels for unix and macOS

### ISSUE THREAD

**Issue by bebound** [aleaxit/gmpy#274]
Currently, users have to install `gmp` `mpfr` `mpc` before install `gmpy`, this is inconvenient.

I have tried to use `cibuildwheel` to create wheels for unix and macOS, and it seems works. So we can publish wheels on pypi.

If this looks fine, I can create a PR. Thank you.

The built wheels are here: https://github.com/bebound/gmpy/actions/runs/93053946

Related issue: https://github.com/aleaxit/gmpy/issues/227

**Comment by casevh** [comment]
This was on my list to do. Please create a PR. I'll take care of adding Windows support.

**Comment by casevh** [comment]
I have made a pre-release available on Github. 

https://github.com/aleaxit/gmpy/releases/tag/gmpy2-2.1.0b6

I am trying to gather feedback on the binary wheels. Assuming no issues are reported, I'll publish this version on PyPi.

**Comment by skirpichev** [comment]
@casevh, probably these wheels can be published on the PyPI (after ~2 month of testing)?  I hope you will add wheels for CPython 3.10, this should be possible now.

**Comment by casevh** [comment]
2.1.0 final is published on PyPi.
