### ISSUE TITLE
test_gmpy2_math.txt hangs on armhf

### ISSUE THREAD

**Issue by murraybd** [aleaxit/gmpy#278]
The Ubuntu autopkgtest infrastructure started seeing failures (timeouts after nearly 3 hours) with the package python-gmpy2 version 2.1.0~b4-1 on armhf architecture. Digging into the tests in gmpy I've identified that the failing test is in test_gmpy2_math.txt and by selectively running tests in that test I've discovered that the failure is with the factorial tests - specifically the following test.

>>> gmpy2.factorial(123456789)
mpfr('inf')

For reasons unclear to me this particular test hangs on armhf. I'm going to leave that specific test running over the weekend but I suspect it won't ever return anything.

**Comment by murraybd** [comment]
I've left the test running for two days and it is still hung.

**Comment by casevh** [comment]
This should be fixed in the main branch. I will be publishing b5 very soon.
