### ISSUE TITLE
Overflows causing `gmp: overflow in mpz type Aborted` instead of Python `OverflowError`

### ISSUE THREAD

**Issue by johanbluecreek** [aleaxit/gmpy#280]
I found that I can cause overflows in the following way

```
$ ipython3
In [1]: from gmpy2 import mpz
In [2]: mpz(8800501504522337) << 16907148584713995
gmp: overflow in mpz type
Aborted
$
```

Working in Python, I would expect the behavior to be to raise a Python `OverflowError` that I can try/except for, instead everything is just aborted and I'm thrown out to the shell:

```
$ ipython3
In [1]: from gmpy2 import mpz
In [2]: try:
   ...:     mpz(8800501504522337) << 16907148584713995
   ...: except:
   ...:     print('anything')
   ...:
gmp: overflow in mpz type
Aborted
$
```

If I'm wrong on the expected behavior or if there is a way of handling this in Python, such comments would be appreciated too.

Just for context (if anyone finds this problem in a similar way to how I did): I'm playing around with using SymPy for Genetic Programming, and sometimes I generate large expressions, that is where I noticed the above. If someone ever gets a similar problem, a work-around is to set the `MPMATH_NOGMPY` environment variable to have `mpmath` avoid `gmpy` that will make `mpmath` raise `MemoryError` instead that one can handle in Python:

```
$ MPMATH_NOGMPY=1 ipython3
In [1]: from sympy import exp
In [2]: try:
   ...:     exp(exp(exp(37.0)))
   ...: except MemoryError:
   ...:     print('anything')
   ...:
anything
In [3]:
```

because otherwise the problem above arises:

```
$ ipython3
In [1]: from sympy import exp
In [2]: try:
   ...:     exp(exp(exp(37.0)))
   ...: except:
   ...:     print('anything')
   ...:
gmp: overflow in mpz type
Aborted
$
```

**Comment by casevh** [comment]
This is the behavior of the GMP library itself. I don't know of a fool-proof fix. The only approach that might work would be to estimate the size of all results and prevent calculations that can overflow.

**Comment by skirpichev** [comment]
> This is the behavior of the GMP library itself.

Yeah.  That's documented in the "Custom Allocation" section of the GMP manual:
```
There’s currently no defined way for the allocation functions to recover from an error
such as out of memory, they must terminate program execution. A longjmp or throwing
a C++ exception will have undefined results. This may change in the future.
```
IIRIC, this was the major reason of rejection GMP-based builtin int's in the CPython.

Perhaps, we should mention that somewhere in the gmpy2 docs (kind of a "Gotchas" section or just in the Introduction).  Then this issue could be closed.

> The only approach that might work would be to estimate the size of all results and prevent calculations that can overflow.

That will slowdown every operation...

**Comment by cfbolz** [comment]
This is a bit of a drive-by comment: I had been wondering for ages how other languages solved this problem. Last year I found out how at least Racket does it. 

[What Racket does](https://github.com/racket/racket/blob/master/racket/src/bc/src/bignum.c#L770) is to implement its big integers is to use the [low-level API of GMP](https://gmplib.org/manual/Low_002dlevel-Functions), which requires the caller to do their own memory management. In order to be able to do that Racket has to take over the allocation and de-allocation of the memory, and indeed they have to compute the size of the resulting ints. They do this to be able to integrate their bigintegers directly with their garbage collector, which can in this way free the memory as usual, without having to interact with gmp at all.

As you can expect, this seems like quite a pain in general (indeed, the Racket file starts with:

```
DANGER! DANGER! DANGER! DANGER! DANGER! DANGER! DANGER! DANGER!

   This code is fragile, due to the Small_Bignum optimization, and
   memory subtleties of bignums.
```

 So I'm not at all saying that `gmpy` should act in any way on this information, I'm just providing context.

**Comment by skirpichev** [comment]
Thanks, @cfbolz!  I've seen your reply in https://discuss.python.org/t/18889 and I would agree that this is "too low-level" for most projects that depend on the GMP library.  That's why even in the Scheme world:
```
$ ulimit -v $((1024*100))
$ guile
...
scheme@(guile-user)> (expt 1000000 10000000)
GNU MP: Cannot allocate memory (size=1090672)
Aborted
```
I think the gmpy2 should be a thin wrapper to the GMP (and friends?).

**Comment by cfbolz** [comment]
ah, thanks for the reminder! I knew I had written that somewhere already but had forgotten where :laughing:. and yes, agreed!

**Comment by skirpichev** [comment]
Hmm, unfortunately the Racket-like approach still doesn't kill dynamic memory allocation by the GMP in ``mpn_*`` functions:
```
sk@note:~/src/gmp $ grep -R TMP_ALLOC mpn/|wc -l
170
sk@note:~/src/gmp $ grep -R TMP_BALLOC mpn/|wc -l
50
```
In the Racket they don't override default memory allocation functions, so in some cases this will trigger abort() calls :(
