### ISSUE TITLE
Provide wheels?

### ISSUE THREAD

**Issue by skirpichev** [aleaxit/gmpy#281]
Since 2.1.0a2 there are no wheels on the pypi or the github releases.

**Comment by bebound** [comment]
According to  #274 , linux and macos should work, but there is problem when trying to build windows wheels.

**Comment by casevh** [comment]
I am now able to build wheels for Windows for Python 2.7 and 3.5 to 3.10. I've only made 64-bit versions but I should be able to make 32-bit versions. Do you think there will be a demand for 32-bit versions?

**Comment by skirpichev** [comment]
I think, if it simplify life for you - keep only 64-bit wheels.  32-bit versions can be added later, per request.

**Comment by casevh** [comment]
I have made a pre-release available on Github. 

https://github.com/aleaxit/gmpy/releases/tag/gmpy2-2.1.0b6

I am trying to gather feedback on the binary wheels. Assuming no issues are reported, I'll publish this version on PyPi.

**Comment by skirpichev** [comment]
@casevh, I've tested this pre-release [here](https://github.com/diofant/diofant/pull/1157).  Only linux binary wheels for 3.9 are used.
