### ISSUE TITLE
a = xmpz(1);a <<= 1; a is mpz(4) !!!

### ISSUE THREAD

**Issue by fsssosei** [aleaxit/gmpy#282]
>>> from gmpy2 import xmpz
>>> a = xmpz(1)
>>> a <<= 1
>>> a
mpz(4)

**Comment by casevh** [comment]
It's a bug. I'll work on a fix.

**Comment by skirpichev** [comment]
@casevh, now this return a correct answer `xmpz(2)`, probably after db7ce2e.  I think, you can close this.
