### ISSUE TITLE
Getting exponent issues

### ISSUE THREAD

**Issue by wjamesjr** [aleaxit/gmpy#288]
`import gmpy2
from gmpy2 import mpfr, digits, get_exp

cf = math.log(10.) / math.log(2.)
print(cf)
gmpy2.get_context().emax = 100000000000000
n1 = mpfr("1.e1000000000")
_, exponent, _ = n1.digits()
exponent2 = get_exp(n1)
print(exponent, exponent2)
n1 = mpfr("1.e10000000000")
_, exponent, _ = n1.digits()
exponent2 = get_exp(n1)
print(exponent, exponent2)
`

New to using gmpy2 but having issues getting mpfr exponents.  Running the above code on MacOS 10.14.6 and using gmpy2 v2.08.  Would expect exponent returned from digits() and get_exp() to match, but the value returned from get_exp() is high by factor of math.log(10.) / math.log(2.).  Also using the .digits() call, the exponent returned is unpredictable if above 1000000000.

The program output I receive is:

3.3219280948873626
1000000000 3321928095
1410065408 33219280949

I would expect the exponent returned by both calls to be the same.

**Comment by casevh** [comment]
The `mpfr` uses binary floating point representation. The line `gmpy2.get_context().emax = 100000000000000` specifies the maximum value as 2**100000000000000. In decimal, the maximum value is ~10**3321928095.

`.digits()` returns (mantissa, exponent, radix). The value for `radix` defaults to 10. `.digits(2)` will return the binary exponent.

`.get_exp()` returns the binary exponent.

**Comment by wjamesjr** [comment]
Thanks, from reading the docs I did not understand that .emax and .emin were binary exponents.  Now, am I correct in trying to convert the binary exponent to radix 10 exponent by:

radix 10 exponent = int( binary_exponent / (math.log(10.) / math.log(2.)))

If so, I am getting a conversion that is one too small in many cases.
Am I doing this right?
Sorry, if I am being dense.

**Comment by casevh** [comment]
It isn't possible to directly convert a binary exponent to a decimal exponent since you are neglecting the impact of the mantissa. To see the exact internal representation, use `.digits(2)` and then compare that to `.digits(10)`.

Can you describe what is your end goal?

**Comment by wjamesjr** [comment]
I like to test and optimize arbitrary precision algorithms.  Currently I am comparing the timing of a Chudnovsky algorithm with a modified Gauss-Legendre algorithm.  An excerpt of the Legendre algorithm is:

`def pi_generate_agm(needed_digits, verbose = False):
    gmpy2.set_context(gmpy2.context())
    error_digits = needed_digits + 4
    cf = math.log(10.) / math.log(2.)
    gmpy2.get_context().precision = int((needed_digits + 10) * cf)
    gmpy2.get_context().emax = int((needed_digits + 2) * cf)
    gmpy2.get_context().emin = int(-(needed_digits + 2) * cf)
    iter = 0
    .........
    .........
    while True:
    	iter += 1
		..........
		..........
        e = e - b
        exponent = int(get_exp(e) / cf)
        if verbose:
            sys.stdout.write('\r')
            sys.stdout.write("iteration: " + str(iter) + ", " + str(-exponent * 2) + " digits")
            sys.stdout.flush()
        if e == 0.0 or exponent * -4 > error_digits:
            if verbose:
                print(" ")
                print("final iteration")
            .........
            .........
            break
    return pi_agm
`

For long running algorithms it is nice to see a running estimate of the number of correct decimal digits, which this does.  The test      if e == 0.0 or exponent * -4 > error_digits:
could be replaced with a test against an error value such as:
error = mpfr("1.E-" + str(needed_digits // 4 + 2))
.............
if e == 0.0 or e < error:
.............

Regardless, the decimal exponent converted from get_exp() is going to be close enough for this application (never off by more than one).

Thanks, for the explanation, we can consider this closed.
