### ISSUE TITLE
You can ask for the original gmpy name on PyPI

### ISSUE THREAD

**Issue by verhovsky** [aleaxit/gmpy#289]
There's [PEP 541](https://www.python.org/dev/peps/pep-0541/) that lets you get the original name of a project if it's abandoned and you've made significant contributions to the fork. See for example https://github.com/pypa/pypi-support/issues/846

**Comment by casevh** [comment]
I actually have the gmpy account on PyPI. gmpy2 was a significant re-write with backwards incompatible changes so I elected to use a different name.
