### ISSUE TITLE
Wrong result gmpy2.invert(x, m) for m = 1 (and m = -1).

### ISSUE THREAD

**Issue by lschoe** [aleaxit/gmpy#304]
A call `invert(x, m)` with `m = 1` should return `0` for any value of `x`, but we get:
```
>>> from gmpy2 import invert
>>> invert(0, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: invert() no inverse exists
```
The same happens for `m = -1`.

The case is correctly handled by GMP, see [`mpz_invert(rop, op1, op2)`](https://gmplib.org/manual/Number-Theoretic-Functions#index-mpz_005finvert), where they note "... (with `rop = 0` possible only when `abs(op2) = 1`, i.e., in the somewhat degenerate zero ring). If an inverse doesn’t exist the return value is zero and `rop` is undefined.". 

So, in case `abs(m) = 1`, the GMP call will always return `success = 0`. A `success = 0` result normally represents a (division) error, but in this corner case it is the actual result.

This relevant `gmpy2` source code can be found around https://github.com/aleaxit/gmpy/blob/eaf017ae71892e85a1c21e3232398736a5bf5bca/src/gmpy2_mpz_misc.c#L999
and I think also around https://github.com/aleaxit/gmpy/blob/eaf017ae71892e85a1c21e3232398736a5bf5bca/src/gmpy2_mpz_misc.c#L1025

**Comment by casevh** [comment]
This has been fixed in the development branch. I'll send a second message when publish the latest beta version along with wheels.

**Comment by lschoe** [comment]
OK, nice! No hurry.

**Comment by casevh** [comment]
Final release of 2.1.0 is out!

**Comment by lschoe** [comment]
Very nice! I've tested 2.1.0 and it works flawlessly.
Great effort that you managed to get all the wheels (incl. Windows) on PyPI now.
Thx a lot.
