### ISSUE TITLE
is_prime() returns True for "negative primes"

### ISSUE THREAD

**Issue by lschoe** [aleaxit/gmpy#312]
Hi, just ran into this small issue (with gmpy2 v2.0.8 and also with v2.1.0b5):
```
>>> from gmpy2 import mpz, is_prime, next_prime
>>> is_prime(-7)
True
>>> is_prime(mpz(-7))
True
>>> is_prime(1 - 2**4423)  # 20th Mersenne prime
True
>>> [is_prime(-a) for a in range(8)]
[False, False, True, True, False, True, False, True]
>>> next_prime(-8)
mpz(2)
```
So, is_prime() returns True for "negative primes" both for Python integers and for gmpy2 mpz integers.
But next_prime() still skips to the first actual prime above -8.

Aside: Mathematica also happens to return True for "negative primes", but there it is documented as the intended behavior.

**Comment by ThomasTNO** [comment]
If we look at `sympy`, negatives are purposely considered **not** prime:  
https://docs.sympy.org/latest/modules/ntheory.html#sympy.ntheory.primetest.isprime

**Comment by casevh** [comment]
I'll make the change in v2.1.2 so it agrees with `sympy`. I just hope the change doesn't break too much existing code.

**Comment by TariqTNO** [comment]
@casevh I just tested this with v2.1.2 and noticed the following:
```
>>> import gmpy2
>>> gmpy2.is_prime(-3)
False
>>> gmpy2.is_prime(gmpy2.mpz(-3))
False
>>> gmpy2.mpz(-3).is_prime()
True
```

The last method should also return `False` I think to make this fix fully consistent.
