### ISSUE TITLE
Update PIP binary builds

### ISSUE THREAD

**Issue by polkovnikov** [aleaxit/gmpy#313]
Looks like PIP binary builds are very outdated, [see here](https://pypi.org/project/gmpy2/#files), there is only Python **3.4** prebuilt version for Windows and none for Linux.

Of course you can pip-install everything from source, but building GMPY2 is quite uneasy, especially for Windows were you have to manually install Visual Studio and install/prebuild all dependend libraries. Many people can't do this. Linux version is easier to build, also prebuilt version is available through `sudo apt install python3-gmpy2`, but it would be great if also Linux prebuilt version is available through pip-install.

Very good updated binary builds of GMPY2 are [available here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#gmpy), I use them often, this website has very good quality of all builds and hundreds of other prebuilt PIP binary packages, which are usually unavailable in PIP. You can just take this build from there, I tested it many times, and place it on PIP.

**Comment by polkovnikov** [comment]
@casevh  Thanks for reply! Just tested this new RC1 gmpy2 `pip install gmpy2==2.1.0rc1`, it gives totally correct results on my quite complex program. Tested on Windows Python 3.9.

Would be great to place some instructions about installing these hidden version, to place instructions on [pypi website](https://pypi.org/project/gmpy2/) and [readthedocs](https://gmpy2.readthedocs.io/en/latest/).

Because I'm sure without these hidden instructions many even advanced programmers like me will not find out how to install binary wheels.

**Comment by polkovnikov** [comment]
@casevh I didn't find any util to list ALL package versions (including non-release) available on PIP, `pip index versions gmpy2` lists only release versions.

But I found out that it is possible to do through public API url [https://pypi.org/pypi/gmpy2/json](https://pypi.org/pypi/gmpy2/json). And I wrote a tiny Python script to print just versions from this JSON:

```
import sys, requests
data = requests.get(f'https://pypi.org/pypi/{sys.argv[1]}/json').json()
print('\n'.join(sorted(data['releases'].keys())))
```

that can be used through `python script.py gmpy2` which prints following versions including non-releases:

```
2.0.0
2.0.0b3
2.0.0b4
2.0.1
2.0.2
2.0.3
2.0.4
2.0.5
2.0.6
2.0.7
2.0.8
2.1.0a1
2.1.0a2
2.1.0a3
2.1.0a4
2.1.0b1
2.1.0b3
2.1.0b4
2.1.0b5
2.1.0rc1
```

**Comment by skirpichev** [comment]
> But the pypi.org website and pip will only
> install "stable" releases by default. And the existence of pre-release
> versions is very well hidden. :(
>
> Binary wheels for Linux, MacOS, and Windows are available for gmpy2
> 2.1.0rc1. The pip syntax is "pip install gmpy2==2.1.0rc1".

It's possible to use instead:
```
pip install --pre gmpy2
```
In this way users get latest published pre-release version.

> I didn't find any util to list ALL package versions (including non-release) available on PIP, pip index versions gmpy2 lists only release versions.

@polkovnikov, here you could also use the `--pre` option:
```
$ pip index versions --pre gmpy2
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
gmpy2 (2.1.0rc1)
Available versions: 2.1.0rc1, 2.1.0b5, 2.1.0b4, 2.1.0b3, 2.1.0b1, 2.1.0a4, 2.1.0a3, 2.1.0a2, 2.1.0a1, 2.0.8, 2.0.7, 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1
  INSTALLED: 2.1.0rc1
  LATEST:    2.1.0rc1 (pre-release; install with `pip install --pre`)
```

**Comment by casevh** [comment]
I have release 2.1.0 which should be easily installable.

**Comment by skirpichev** [comment]
@casevh, probably this can be closed.

**Comment by polkovnikov** [comment]
@casevh Thanks, this solves the issue, although it was already solved through usage of `--pre`, but now even `--pre` is not needed,  due to release of GMPY2, great! Closing...
