### ISSUE TITLE
Regression: mpq.__pow__ should return NotImplemented

### ISSUE THREAD

**Issue by oscarbenjamin** [aleaxit/gmpy#319]
This has just popped up in SymPy CI: https://github.com/sympy/sympy/pull/22657#issuecomment-992335103

With gmpy2 version 2.1.0 the `mpq.__pow__` method has been changed to raise `TypeError` instead of returning `NotImplemented`:
```python
In [3]: from gmpy2 import mpq

In [4]: from sympy import Rational

In [5]: mpq(8, 1).__pow__(Rational(1, 3))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-9b167a58b29f> in <module>
----> 1 mpq(8, 1).__pow__(Rational(1, 3))

TypeError: unsupported operand type(s) for ** or pow()
```
With gmpy 2.0.8 this correctly returns `NotImplemented`:
```python
In [1]: from sympy import Rational

In [2]: from gmpy2 import mpq

In [3]: mpq(8, 1).__pow__(Rational(1, 3))
Out[3]: NotImplemented
```
This is needed so that SymPy's `Rational` type can cooperate with mpq using `__rpow__`:
```python
In [4]: Rational(1, 3).__rpow__(mpq(8, 1))
Out[4]: 2

In [5]: mpq(8, 1) ** Rational(1, 3)
Out[5]: 2
```

**Comment by oscarbenjamin** [comment]
I guess it comes from here:
https://github.com/aleaxit/gmpy/blob/1928e1bcec53eae10a0a0dcd9f5cd027dd481e7c/src/gmpy2_pow.c#L515-L535

**Comment by oscarbenjamin** [comment]
Also the standard error message is better as it includes the types:
```python
In [6]: class A: pass

In [7]: A() ** 2
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-9845e827204c> in <module>
----> 1 A() ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'A' and 'int'
```

**Comment by oscarbenjamin** [comment]
I suppose SymPy CI should probably track prereleases of gmpy2 because we would have picked this up with gmpy2 2.1.0rc2. In fact with rc1 if you try this then it shows a really nasty bug that consumes all the memory in the computer and hardly even responds to Ctrl-C:
```python
from sympy import Rational
from gmpy2 import mpq
mpq(8, 1) ** Rational(1, 3)
```

**Comment by casevh** [comment]
I've just committed a fix. I will release 2.1.1 soon.

**Comment by casevh** [comment]
I have pushed 2.1.1 to PyPi.

**Comment by oscarbenjamin** [comment]
Thanks!
