### ISSUE TITLE
Support for erfinv

### ISSUE THREAD

**Issue by TedTed** [aleaxit/gmpy#325]
Hi, we are possibly interested in using gmpy for an application related to differential privacy; but we would need support for the `erfinv` function.

- How difficult would it be to add support for this to `gmpy`? Do I understand correctly that we could simply add the corresponding MPFR binding like is done for the other functions, or are there unexpected subtleties?
- How fast could we expect the turnaround to be for PR review, merging, and releasing?

Thanks a ton in advance!

**Comment by casevh** [comment]
I don't see `erfinv` listed in the MPFR documentation. Do you have an implementation for it?

The source code must be licensed under LGPLv3+ to allow it to be bundled into `gmpy2`. There maybe other options if that is not possible.

**Comment by TedTed** [comment]
Sorry, yes, I was looking at different arbitrary-precision computation projects and mixed things up. Thanks for letting us know what the requirements would be if we end up sending a PR to MPFR!
