### ISSUE TITLE
Unexpected mpq() behaviour.

### ISSUE THREAD

**Issue by enigmatic-code** [aleaxit/gmpy#334]
Passing an mpq object to mpq() results in the original object being modified and returned.

This behaviour is different to fractions.Fraction, and is probably not what people expect to happen.

e.g. This is expected behaviour:

```
>>> Q = fractions.Fraction
>>> x = Q(3, 2)
>>> y = Q(x, 2)
>>> x
Fraction(3, 2)
>>> y
Fraction(3, 4)
>>> id(x) == id(y)
False
```

This is mpq() behaviour:

```
>>> gmpy2.version()
'2.1.2'
>>> Q = gmpy2.mpq
>>> x = Q(3, 2)
>>> y = Q(x, 2)
>>> x
mpq(3, 4)
>>> y
mpq(3, 4)
>>> id(x) == id(y)
True
```

**Comment by casevh** [comment]
Thanks for the report. I'm finishing up the fix right now.

**Comment by casevh** [comment]
The second version of the fix has been committed. Thanks for the report.
