### ISSUE TITLE
Possible incorrect calculations in subnormalize mode

### ISSUE THREAD

**Issue by ozankabak** [aleaxit/gmpy#335]
Consider the following snippet:
```python
from gmpy2 import get_context, div_2exp, mpfr, next_below

get_context().precision = 2
get_context().emin = -2
get_context().emax = 3

get_context().subnormalize = False
print(div_2exp(mpfr(3), 4))
print(next_below(mpfr(0.25)))

get_context().subnormalize = True
print(div_2exp(mpfr(3), 4))
print(next_below(mpfr(0.25)))
```
which produces
```
0.19
0.19
0.25
0.12
```
It seems as if non-subnormalize mode includes the value 0.19 (mantissa 3, exponent -4), but subnormalize mode does not include it. Is this correct behavior or indicative of a bug? Thanks.

**Comment by casevh** [comment]
I think it is the correct behavior.

Let's display both the decimal and binary values:

```python
from gmpy2 import get_context, div_2exp, mpfr, next_below

get_context().precision = 2
get_context().emin = -2
get_context().emax = 3

get_context().subnormalize = False
a = div_2exp(mpfr(3), 4)
b = next_below(mpfr(0.25))

get_context().subnormalize = True
c = div_2exp(mpfr(3), 4)
d = next_below(mpfr(0.25))

a, a.__format__('b')
b, b.__format__('b')
c, c.__format__('b')
d, d.__format__('b')
```

The output is:

```
(mpfr('0.19',2), '1.1p-3')
(mpfr('0.19',2), '1.1p-3')
(mpfr('0.25',2), '1p-2')
(mpfr('0.12',2), '1p-3')
```
For 'a' and 'b', the binary output uses two bits ("1.1") but the exponent is -3 which is less than 'emin'. If the exponent is restricted  to 'emin', the binary output for 'a' and 'b' would be '0.11p-2'. But this requires 3 bits ("0.11"). Subnormalize needs to round to 2 bits. `div_2exp` follows the honors the rounding mode (round ties to even) so '0.11' is rounded to '1.0' or '1p-2'. 'next_below' just  uses the next smaller so '0.11' becomes '0.10' or '1p-3'.

I think I got the analysis correct. But the subtleties floating point representations never cease to surprise me.

**Comment by ozankabak** [comment]
I am closing this issue as @casevh gave an accurate analysis of what is going on -- there does not seem to be a bug here.
