### ISSUE TITLE
Would you consider releasing the 2.1.3 version?

### ISSUE THREAD

**Issue by tanjuntao** [aleaxit/gmpy#343]
It's been a while since the release of the 2.1.2 version, and some new features such as `powmod_list()` are newly included since then. Although we can manually download the 2.1.3 build wheels from GitHub Actions Tab, it's not presented in PyPI resulting that we cannot automatically install the 2.1.3 version when working with `pip` and `requirements.txt` in a Python project. It's a bit inconvenient. 

So would you consider releasing the 2.1.3 version and publishing it to PyPI?

**Comment by casevh** [comment]
I just fixed a couple issues with Windows builds and Python 3.11. I will try to get a release out soon.

**Comment by tanjuntao** [comment]
Great, really appreciate your work

**Comment by casevh** [comment]
I am just finishing the documentation updates. Would it be acceptable to rename "powmod_list" to "powmod_base_list" to correspond to "powmod_exp_list"? This would pave the way for "powmod_base_exp_list".

As another note, I want to focus on vector operations similar to powmod*list. I may rename these functions at that time but the capability will always exist.

**Comment by tanjuntao** [comment]
Yes, it is more clear and works good for me.

**Comment by skirpichev** [comment]
@casevh, probably this can be closed.
