### ISSUE TITLE
Adding _sympy_ method to mpfr type for robust interoperability with sympy

### ISSUE THREAD

**Issue by ozankabak** [aleaxit/gmpy#353]
Hello. The `mpfr` type does not seem to have a `_sympy_` method, which creates problems when using `gmpy2` in tandem with `sympy`. Consider the snippet:
```python
import sympy
from gmpy2 import mpfr

x = mpfr("-1e-800") in sympy.sets.Interval(0, sympy.oo)
```
This results in `x` being `True`, which shouldn't be the case. I tracked the reason down to `mpfr` type not having a `_sympy_` method, which results in `mpfr` instances being converted to `float`, losing precision in the process.

I found others suffering from the same issue in different use cases as well -- check out this [SO post](https://stackoverflow.com/questions/28636499/sympy-polynomials-with-mpfr-coefficients).

A fix will be much appreciated, thank you!

**Comment by skirpichev** [comment]
The Sympy has defined converters for the mpz & the mpq types [here](https://github.com/sympy/sympy/blob/c25ecf0ef7c63ec8b9cb416544a682c758fcc5f2/sympy/core/numbers.py#L4451-L4462).  I don't see reasons why this can't be the case for the mpfr type too.

I suggest closing this issue and reopening an issue against the sympy repo.

**Comment by casevh** [comment]
I am planning to add fast conversion functions between `mpf` and mpfr` types. I'll leave this open until I add them and then I'll close this issue.

**Comment by ozankabak** [comment]
Thank you
