### ISSUE TITLE
Expose mpz_probab_prime_p() int return values from is_prime()

### ISSUE THREAD

**Issue by typicalTYLER** [aleaxit/gmpy#354]
I think it makes sense to expose the integer return value that is calculated already in gmp's `mpz_probab_prime_p`. As certainty of a prime is useful for certain algorithms.

From gmp: ```Return 2 if n is definitely prime, return 1 if n is probably prime (without being certain), or return 0 if n is definitely non-prime.```

For instance, I am trying to quickly collate all "likely" semiprimes of a certain characteristic, and doing a quick primality test after dividing out a small factor would allow me to be _**certain**_ the number is a semiprime (or not), only if we are **_certain_** the quotient is prime (2) (or composite (0)), but if we are unsure (1), we don't want to exit the function yet.

Or if that change would be too breaking, you could add a default parameter to the function signature to retain the old behavior by default, and allow the user to request the more granular return type.

Or possibly expose another function that has a more granular return type to not clutter the interface.

**Comment by casevh** [comment]
How large are your semiprime values?

GMP use the BPSW algorithm and returns 2 when the input is less than the validated upper limit for GMP's implementation of BPSW. The upper limit is currently ~2.12 * 10^15. Would access to the return value still help you?

**Comment by typicalTYLER** [comment]
Yes! It varies, but ~2.12*10^15 would definitely be in the range I regularly test. Knowing this value, it seems like I could just wrap gmpy2.is_prime() and return 1 or 2 if true based off argument size. (Which I probably will for the time being). But having direct access to the API would be nicer, in case gmp moves to a different implementation, or really just to be cleaner!

**Comment by skirpichev** [comment]
gmpy2 is a wrapper, so access to the wrapped API is assumed.

Without a backward compatibility constraint, I would suggest mapping C->Python returned values as `2->True, 1->None, 0->False`.  But now...  Maybe we could provide a boolean option like `strict` with such an output convention?

**Comment by casevh** [comment]
I'd like to propose the following:

1) Add `is_probab_prime` and let it return 0, 1, or 2.

2) Update the documentation of for `is_prime` and state that `is_probab_prime` is the official wrapper for the GMP function and that `is_prime` may change in the future. I think it would be interesting to implement an improved version of the the BPSW test describes in this article: https://arxiv.org/abs/2006.14425v2

Comments?

**Comment by brubsby** [comment]
I'm happy with that result!

**Comment by typicalTYLER** [comment]
I'm happy with that result!
