### ISSUE TITLE
Missing methods on mpz c.f. int

### ISSUE THREAD

**Issue by skirpichev** [aleaxit/gmpy#357]
The documentation claims that "It should be a drop-in replacement for Python’s long type."  Unless I misunderstood it, the mpz type must implement all public methods for the int, which is not the case for recent CPython:
```
$ python
Python 3.11.1+ (heads/3.11:ba88628808, Jan 14 2023, 08:40:06) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gmpy2
>>> for m in dir(int):
...     if m not in dir(gmpy2.mpz):
...         print(m)
... 
__getnewargs__
as_integer_ratio
from_bytes
to_bytes
```
Last three methods are missing.

**Comment by sfornengo** [comment]
It will be awesome, I currently cast mpz to python int to get bytes: int(x).to_bytes(32,'big') and it is pretty slow...

**Comment by skirpichev** [comment]
BTW, here some simple benchmarks (including my draft patch for this bug):
```
$ python -m timeit -s 'from math import factorial' -s 'a = factorial(57)' 'a.to_bytes(32)'
1000000 loops, best of 5: 281 nsec per loop
$ python -m timeit -s 'from gmpy2 import fac' -s 'a = fac(57)' 'a.to_bytes(32)'
500000 loops, best of 5: 772 nsec per loop
$ python -m timeit -s 'from gmpy2 import fac' -s 'a = fac(57)' 'int(a).to_bytes(32)'
500000 loops, best of 5: 863 nsec per loop
$ python -m timeit -s 'from gmpy2 import fac, to_binary' -s 'a = fac(57)' 'to_binary(a)'
500000 loops, best of 5: 444 nsec per loop
```

**Comment by casevh** [comment]
For clarification, `to_binary` converts all `gmpy2` types such that they can be recovered by `from_binary`. It should be (somewhat) platform neutral. 64-bit systems should be able to read binary blobs created on 32-bit system and vice-versa.

I'll review the pull request.

**Comment by sfornengo** [comment]
@skirpichev, yes but to_bytes() and to_binary() have different meaning.
to_binary() takes care of a portable import/export and so adds a header. It needs a lot of operations to get a result similar to the python int.to_bytes()

Why mpz.to_bytes() is so slow vs int.to_bytes() ?

**Comment by skirpichev** [comment]
> Why mpz.to_bytes() is so slow vs int.to_bytes() ?

For above tests it seems to be connected with the argument parsing and (?) METH_FASTCALL calling convention for int.to_bytes (I'll try to build the gmpy2 with this patch for the v3.6 of CPython to verify that.).

**Comment by skirpichev** [comment]
Here is v3.6 on same host:
```
$ python -m timeit -s 'from math import factorial' -s 'a = factorial(57)' 'a.to_bytes(32, "big")'
1000000 loops, best of 3: 0.776 usec per loop
```

**Comment by sfornengo** [comment]
Wow, METH_FASTCALL worth it!

**Comment by casevh** [comment]
Some comments on METH_FASTCALL. I converted _mpmath_normalize to use the vectorcall protocol. _mpmath_normalize requires exactly 6 positional arguments. There are no keyword arguments. METH_FASTCALL decreased the function call overhear by ~30ns.

to_bytes/from_bytes take keyword arguments so the savings may be better. I plan to do some experimentation this weekend.

**Comment by skirpichev** [comment]
On Thu, Feb 09, 2023 at 09:32:02PM -0800, casevh wrote:
>    Some comments on METH_FASTCALL. I converted _mpmath_normalize to use the
>    vectorcall protocol. _mpmath_normalize requires exactly 6 positional
>    arguments. There are no keyword arguments. METH_FASTCALL decreased the
>    function call overhear by ~30ns.

For positional-only it's easy, I'll post some benchmarks in the closed pr.
Unfortunately, there is no (yet) a public api to help handling kwargs
with METH_FASTCALL.  See e.g.
https://github.com/python/cpython/issues/83528

>    to_bytes/from_bytes take keyword arguments so the savings may be better.

Without keyword arguments it's definitely better.  Yet, it seems that
the python's to_bytes still faster then the mpz_export (for natural numbers
and with any byteorder).  (But better then int(z).to_bytes, of course.)

**Comment by skirpichev** [comment]
Here is an initial version with METH_FASTCALL:
https://github.com/skirpichev/gmpy/tree/fix-357

```
$ python -m timeit -s 'from math import factorial' -s 'a = factorial(57)' 'a.to_bytes(32)'
1000000 loops, best of 5: 276 nsec per loop
$ python -m timeit -s 'from gmpy2 import fac' -s 'a = fac(57)' 'a.to_bytes(32)'
500000 loops, best of 5: 485 nsec per loop
$ python -m timeit -s 'from gmpy2 import fac' -s 'a = fac(57)' 'int(a).to_bytes(32)'
500000 loops, best of 5: 810 nsec per loop
```
