### ISSUE TITLE
Incorrect interpretation of numbers with high bases

### ISSUE THREAD

**Issue by sphynkx** [aleaxit/gmpy#379]
Incorrect interpretation of numbers with high bases - letters handle case sensitively and some numbers turn out the same (after upper() for example). And in addition, lowercase only in range a..f:

>>> import gmpy2
>>> for i in range(100): print(i, gmpy2.xmpz(i).digits(42), gmpy2.xmpz(i).digits(42).upper())
...
7 7 7
8 8 8
9 9 9
10 A A
11 B B
12 C C
...
33 X X
34 Y Y
35 Z Z
36 a A
37 b B
38 c C
39 d D
40 e E
41 f F
42 10 10
43 11 11
...

gmpy2.mpz(i) has the same result..

Tested env: 
Win10
python 3.8
gmpy2 2.1.5

**Comment by skirpichev** [comment]
I don't sure it's an "incorrect".  Same for gmplib:
```
$ cat a.c
#include <stdio.h>
#include <gmp.h>

int
main(int argc, char* argv[])
{
    int base = 42, x[2] = {35, 36};
    mpz_t n;
    mpz_init(n);
    for (int i = 0; i < 2; i++) {
        mpz_set_si(n, x[i]);
        fprintf(stdout, "%d: ", x[i]);
        mpz_out_str(stdout, base, n);
        fprintf(stdout, "\n");
    }
    mpz_clear(n);
    return 0;
}
$ cc a.c -lgmp && ./a.out 
35: Z
36: a
```
"For bases up to 36, case is ignored; upper-case and lower-case letters have the same value. For bases 37 to 62, upper-case letter represent the usual 10..35 while lower-case letter represent 36..61." (c) https://gmplib.org/manual/I_002fO-of-Integers

But maybe we should expand the digits docstring with this remark.

**Comment by sphynkx** [comment]
Xmm.. turns out that you cannot apply the upper() operator to numbers.. Yes, it really would be reasonable to reflect this moment in the documentation, perhaps even in a separate section and especially case about the nomenclature of numbers. Because there is apparently no single and clear nomenclature for writing numbers with a non-standard base - there exist recommendations to exclude 'I' and 'O' (but for some reason not lowercase 'L') so as not to confuse them with similar numbers. However the gmplib docs doesn't specify that.
Anyway, there is still a problem in the code - lowercase letters are iterated from 'a' to 'f', while uppercase letters are in the full range.

**Comment by skirpichev** [comment]
> Xmm.. turns out that you cannot apply the upper() operator to numbers..

You can.  But in general, this will be a _different_ digit.

> Yes, it really would be reasonable to reflect this moment in the documentation

On another hand, the gmpy2 is just a wrapper.  So, in case of doubts - see the documentation of the GMP library (or MPFR/MPC).

> However the gmplib docs doesn't specify that.

They do.  That specification was quoted in [the above post](https://github.com/aleaxit/gmpy/issues/379#issuecomment-1430747476).

> lowercase letters are iterated from 'a' to 'f'

No.  That's only because you have used base=42.
```
>>> mpz(35).digits(62)
'Z'
>>> mpz(61).digits(62)
'z'
```
