### ISSUE TITLE
Incompatible (with int) parsing of the sign in the mpz constructor

### ISSUE THREAD

**Issue by skirpichev** [aleaxit/gmpy#381]
```
>>> int('+1')
1
>>> mpz('+1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid digits
```
while
```
>>>>> int('-1')
-1
>>> mpz('-1')
mpz(-1)
```
"Optionally, the string can be preceded by + or - (with no space in between), have leading zeros, be surrounded by whitespace, and have single underscores interspersed between digits." (c) CPython docs

**Comment by skirpichev** [comment]
Another example:
```
>>> int('  0xA',base=0)
10
>>> mpz('  0xA',base=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid digits
```
BTW, base=0 is incompatible with the int's base=10 default.

**Comment by casevh** [comment]
Python and GMP handle embedded white space differently. They both ignore leading and trailing white space. But Python considers embedded white space an error while GMP ignores embedded white space. 

The general rule is that gmpy2 should always return the same result as Python if no exception is raised by Python. Raising an exception when Python doesn't is a bug. Returning a "reasonable" value when Python raises an exception is acceptable (at least it is to me).

I think striping all white space is fine and matches the current behavior. But we won't match the Python exceptions for 
embedded white space and I don't think it is worth changing GMP's behavior.

I also prefer the default of base=0. It is easier for converting strings that include the leading base indicators.

**Comment by skirpichev** [comment]
>    The general rule is that gmpy2 should always return the same result as
>    Python if no exception is raised by Python. Raising an exception when
>    Python doesn't is a bug. Returning a "reasonable" value when Python raises
>    an exception is acceptable (at least it is to me).

Sure, that was the rule I kept in mind.

> I think striping all white space is fine and matches the current behavior.

Probably, this does make sense for all constructors.

>    I also prefer the default of base=0. It is easier for converting strings
>    that include the leading base indicators.

My fault.  That difference does matter only where Python raises exceptions (e.g. `int('0x10')).
