### ISSUE TITLE
gmpy2.xmpz bit reverse padding

### ISSUE THREAD

**Issue by brubsby** [aleaxit/gmpy#385]
I've been trying to use the xmpz type to bit reverse all numbers from 0...2^n-1, and I can't seem to figure out how to do this such that the numbers are padded to n digits.

The code example in the documentation says: 
```py
>>> bin(a)
'0b10001111100'
>>> a[::] = a[::-1]
>>> bin(a)
'0b111110001'
```

which would be fine if we wanted n=11 for an 11 bit number, but if we want to do this as a 12 bit number, it of course would not work with the above example. There's a line in the docs about padding a number by using the stop index in slice, but I can't seem to get it to work, even if I try to things like `a[:n:] = a[::-1]`, `a[:n:] = a[n-1:-1:-1]`, etc etc.

maybe this would work correctly:
```py
n=12
a = gmpy2.xmpz(1148)
b = gmpy2.xmpz()
for bit in a.iter_set():
    other = b.bit_set(n-bit-1)
bin(a)
'0b10001111100'
bin(b)
'0b1111100010'
```
but I assume using slice operators would be the point of this type, and this could possibly slower, but I'm not certain. But regardless I would like to know how to do this with slice operators!

Thanks!

**Comment by casevh** [comment]
GMP does not have the concept of fixed length integers. Just assume that all leading zeros are removed. You will need to track the expected precision manually.
