### ISSUE TITLE
Argument order yn() and jn() inconsistent with MPFR and mpmath

### ISSUE THREAD

**Issue by casevh** [aleaxit/gmpy#401]
The order of the arguments to the gmpy2 functions yn() and jn() are (mpfr, order_of_Bessel_function). Both MPFR and mpmath use (order_of_Bessel_function, mpfr).

Is this worth changing and risk breaking existing code?

Replace them with besselj() and bessely() to match mpmath?

Open to any other ideas.

**Comment by skirpichev** [comment]
>  Both MPFR and mpmath use (order_of_Bessel_function, mpfr).

Also, e.g. Mathematica, maple, matlab, libm's extensions.  Almost anywhere.

> Is this worth changing and risk breaking existing code?

Uneasy decision.  On one hand, people could read the documentation.  On another hand, the gmpy2 is a wrapper to the MPFR.  Then, probably it should follow to conventions of MPFR interfaces (function names, argument order, etc).  Also, people could expect usual mathematical conventions for gmpy2 functions (and the current for jn/yn() is _very_ unusual).

I'm +0 for changing (ditto for other similar cases).

> Replace them with besselj() and bessely() to match mpmath?

No, as the gmpy2 is not an interface to the mpmath.

**Comment by skirpichev** [comment]
Perhaps, this should be closed with 175fa58, @casevh?  Or do you like to provide some smooth transition to deal with the backward compatibility?  BTW, in some sense the former behaviour could be considered as a bug...

**Comment by casevh** [comment]
I will close it. I consider the previous behavior a bug.

I detect the use of (mpfr, int) as the old calling convention and raise an error that states the argument order has changed. This should catch all uses of the old convention except if both arguments are integers.
