### ISSUE TITLE
Breaking changes in Python 3.12.0a7 release

### ISSUE THREAD

**Issue by casevh** [aleaxit/gmpy#405]
I was doing final testing before releasing gmpy2 2.2.0a1. Significant test failures.

IIRC, I last tested with 3.12.0a4 and that was successful.

I still plan to release gmpy2 2.2.0.a1 but without any wheels for 3.12.

Will update when I learn more.

**Comment by skirpichev** [comment]
Test failures in the master (we test 3.12-dev on MacOS): https://github.com/aleaxit/gmpy/actions/runs/4780338278/jobs/8498017005

**Comment by skirpichev** [comment]
Last successful build: https://github.com/aleaxit/gmpy/actions/runs/4550495062/jobs/8023567850
Was on: https://github.com/actions/python-versions/releases/download/3.12.0-alpha.6-4362036571/python-3.12.0-alpha.6-darwin-x64.tar.gz

**Comment by skirpichev** [comment]
@casevh, this was broken by https://github.com/python/cpython/commit/7559f5fda94ab568a1a910b17683ed81dc3426fb from https://github.com/python/cpython/pull/102464

**Comment by skirpichev** [comment]
@casevh, draft patch in https://github.com/skirpichev/gmpy/tree/adapt-for-3.12a7 (tests pass for me locally)

I'll open a pr tomorrow.
