### ISSUE TITLE
Add function csqrt

### ISSUE THREAD

**Issue by daedalus** [aleaxit/gmpy#407]
Please,
Add a function that computes ceil(sqrt(n)).
Much appreciated.

**Comment by skirpichev** [comment]
The gmpy2 is a wrapper for GMP, MPFR and MPC libraries.  I doubt that there exists some function, that corresponds to your proposal.   Hence, I think it's better to reject it.

BTW, if you are interested in integer values of n - you could use the isqrt function.

**Comment by daedalus** [comment]
ok, thanks
