### ISSUE TITLE
Is the `is_strong_bpsw_prp` code correct?

### ISSUE THREAD

**Issue by haru-44** [aleaxit/gmpy#423]
The `is_strong_bpsw_prp` is described as follows

https://github.com/aleaxit/gmpy/blob/016dc985202f2186bf924e80eacdfb14ece17b38/src/gmpy_mpz_prp.c#L1518-L1521

On the other hand, it calls `GMPY_mpz_is_selfridge_prp` as follows

https://github.com/aleaxit/gmpy/blob/016dc985202f2186bf924e80eacdfb14ece17b38/src/gmpy_mpz_prp.c#L1577

I think I should call `GMPY_mpz_is_strongselfridge_prp`, am I mistaken?

**Comment by casevh** [comment]
You are correct. A fix has been committed. I will be release version 2.2.0a1 as soon as I can.
