### ISSUE TITLE
complex conjugate crash

### ISSUE THREAD

**Issue by achan001** [aleaxit/gmpy#434]
[Is the fix applied to gmpy2?](https://github.com/aleaxit/gmpy/issues/194)

I downloaded [WinPython 3.8.9](https://winpython.github.io/) for my Win7 laptop, the bug still there.
```
py3> import gmpy2
py3> gmpy2.version()
'2.0.8'
py3> gmpy2.mpc('1+2j').conjugate() # system crash
```

And, same bug for Python 2.6.6
You had gmpy2 2.0.9 specially made for my Python 2.6.6, a long time ago.
```
py2> import gmpy2
py2> gmpy2.version()
'2.0.9'
py2> gmpy2.mpc('1+2j').conjugate() # system crash

**Comment by casevh** [comment]
Yes, it is fixed.

>>> gmpy2.mpc('1+2j').conjugate()
mpc('1.0-2.0j')

**Comment by achan001** [comment]
I updated gmpy2 with **gmpy2-2.1.5-cp38-cp38-win_amd64.whl**
It work now! Thanks!

This is my first uninstall/install using "WinPython Control Panel.exe"
Drag and drop feature is nice, but the process is scary.
It seems to hang the machine ... but it did finished the job.
