### ISSUE TITLE
Invalid mpq.__float__?

### ISSUE THREAD

**Issue by skirpichev** [aleaxit/gmpy#498]
Consider following example:
```pycon
>>> from gmpy2 import mpq
>>> from fractions import Fraction
>>> float(Fraction(9, 5))
1.8
>>> float(mpq(9, 5))
1.7999999999999998
```
It seems, gmpy2 uses mpq_get_d(), which "Convert op to a double, truncating if necessary (i.e. rounding towards zero)".  While Python does round to nearest.

Indeed:
```pycon
>>> mpz(9)/mpz(5)
mpfr('1.8')
>>> ctx = gmpy2.get_context()
>>> ctx.round=gmpy2.RoundToZero
>>> mpz(9)/mpz(5)
mpfr('1.7999999999999998')
```

I'll provide a patch.

**Comment by skirpichev** [comment]
@casevh, will you include this (57378b6178) in the next point release?

**Comment by casevh** [comment]
Yes. I'll bump the version number to 2.2.2rc1 and will make a release when
we don't think there are any more fixes required.

**Comment by skirpichev** [comment]
@casevh, do you think it's a good idea to keep the master branch for 2.2.x point releases?  I believe it's better to use a dedicated branch (say, 2.2) and cherry-pick only some commits from the master branch.

**Comment by skirpichev** [comment]
> Is a fix for the fallthrough warnings needed for 2.2.2?

If you meant commentaries, I think it's ok: that's just a couple of commentaries:)

But if you about #502 - no.  This PR looks unsuitable even for the master, unless OP provide a portable way to do deal with such warnings.  I don't think we should require C23, thus probably this PR should be rejected.
