### ISSUE TITLE
Intentional fallthroughs?

### ISSUE THREAD

**Issue by r-barnes** [aleaxit/gmpy#501]
Are these fallthroughs intentional? If so, can we mark them with `__attribute__((fallthrough))` so that `-Wimplicit-fallthrough` will pass with them. If not, can we add `break` to fix the bug(s)?

https://github.com/aleaxit/gmpy/blob/30f6ef6d3f600efb46516844bc098d682f8833d2/src/gmpy2_mpmath.c#L290
https://github.com/aleaxit/gmpy/blob/30f6ef6d3f600efb46516844bc098d682f8833d2/src/gmpy2_mpmath.c#L296
https://github.com/aleaxit/gmpy/blob/30f6ef6d3f600efb46516844bc098d682f8833d2/src/gmpy2_mpmath.c#L298

**Comment by skirpichev** [comment]
> Are these fallthroughs intentional?

Absolutely.
