### ISSUE TITLE
support in using gmpy2

### ISSUE THREAD

**Issue by DiTo97** [aleaxit/gmpy#509]
I have been working on [alphacodings](https://github.com/DiTo97/alphacodings), a very small package for alphabetic-only encodings, which relies heavily on string-to-base256-int-conversion, and I have started [using gmpy2](https://github.com/DiTo97/alphacodings/tree/13-support-GMP-for-variable-size-numbers) to make the algorithms faster and faster.

since it's the first time I am using the package, and I am trying to optimize the codebase as much as possible:
- do you have any suggestions for the [gmpy2 implementation](https://github.com/DiTo97/alphacodings/tree/13-support-GMP-for-variable-size-numbers/alphacodings/_fastest)? am I using it in the best way possible?

I have been trying to implement a [C++ version](https://github.com/DiTo97/alphacodings/tree/13-support-GMP-for-variable-size-numbers/src) with pybind11 bindings and have GMP automatically [bundled at build time](https://github.com/DiTo97/alphacodings/blob/13-support-GMP-for-variable-size-numbers/buildext.py), without requiring the user to manually install it in its system, but I am not making a lot of progress. ATM, I am using scikit-build-core as backend, but I am flexible for change if necessary, so I was wondering if you had any pointers for that, as you do something similar in gmpy2, albeit using cython for source code bindings/translation.

**Comment by skirpichev** [comment]
> do you have any suggestions for the [gmpy2 implementation](https://github.com/DiTo97/alphacodings/tree/13-support-GMP-for-variable-size-numbers/alphacodings/_fastest)?

Hard to say.  In https://github.com/DiTo97/alphacodings/blob/13-support-GMP-for-variable-size-numbers/alphacodings/_native/common.py you are using to_bytes/from_bytes.  You can try to do same with mpz.  Probably, this will be slightly faster.

> am I using it in the best way possible?

I'm not sure, that your code is working, for example:
```pycon
Python 3.13.0rc1+ (heads/3.13:bd29ce8509, Aug 29 2024, 15:30:15) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def base256_int_to_string(number):
...     B = (number.bit_length() + 7) >> 3
... 
...     string = number.to_bytes(B, "big")
...     return string.decode("utf-8")
... 
>>> base256_int_to_string(1234)
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    base256_int_to_string(1234)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "<python-input-0>", line 5, in base256_int_to_string
    return string.decode("utf-8")
           ~~~~~~~~~~~~~^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 1: unexpected end of data
>>> base256_int_to_string(23*26**2 + 2*26 + 9)
Traceback (most recent call last):
  File "<python-input-10>", line 1, in <module>
    base256_int_to_string(23*26**2 + 2*26 + 9)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "<python-input-0>", line 5, in base256_int_to_string
    return string.decode("utf-8")
           ~~~~~~~~~~~~~^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 1: invalid start byte
```

**Comment by DiTo97** [comment]
@skirpichev are you sure those are valid base256 integers, or rather, valid bytes that the UTF-8 codec can properly decode back to string?

I have never encountered any errors doing:
```python
base256_int_to_string(string_to_base256_int(string))
```

with any input string.

> Hard to say. In https://github.com/DiTo97/alphacodings/blob/13-support-GMP-for-variable-size-numbers/alphacodings/_native/common.py you are using to_bytes/from_bytes. You can try to do same with mpz. Probably, this will be slightly faster.

could you share a snippet of that? I had tried something similar but I do remember having issues with gmpy maybe handling up to base64 integers in the from/to bytes conversion, not higher.

**Comment by skirpichev** [comment]
> are you sure those are valid base256 integers

Ah, indeed)

> could you share a snippet of that?

In ``_native`` folder you have:
```python
def base256_int_to_string(number: int) -> str:
    B = (number.bit_length() + 7) >> 3
    
    string = number.to_bytes(B, "big")
    return string.decode("utf-8")


def string_to_base256_int(string: str) -> int:
    return int.from_bytes(string.encode(), "big")
```
You can do replace ``int`` -> ``mpz``.

> I had tried something similar but I do remember having issues with gmpy

If this will work differently from CPython's methods - it's a bug.  Feel free to report.

> maybe handling up to base64 (or was it base62?) integers

to_bytes/from_bytes has nothing related to conversion to a different base.  Internally, both GMP and CPython use positional representation of bigints, but with very big base (see sys.int_info).

**Comment by DiTo97** [comment]
> If this will work differently from CPython's methods - it's a bug. Feel free to report.

sure! will test it out and report back

**Comment by DiTo97** [comment]
@skirpichev just works, wow.

I have tested converting back and forth a 1M-character-long string and got a whopping speedup of **8000x**!

BTW, I set you as commit co-author. TBH, I'm not even sure it's necessary to implement it in C/C++ anymore, given how fast the algorithm just got.

**Comment by skirpichev** [comment]
I would guess, this issue can be closed?
