### ISSUE TITLE
Memory leak when using gmpy2.ieee context manager

### ISSUE THREAD

**Issue by thomaswucher** [aleaxit/gmpy#515]
When using the ieee context manager repeatedly, memory is leaked using gmpy latest master branch (c7629dd). The problem can be reproduced in the following way:

```
$ ulimit -v $((1024*256))
$ cat test.py
import gmpy2

while True:
    with gmpy2.ieee(64):
        x = 1
$ python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
MemoryError
```

The test case works fine (i.e. runs forever) when using gmpy 2.1.5. Thanks for looking into this!

**Comment by thomaswucher** [comment]
I did try to do a git bisect, but unfortunately many commits in the range where the issue was introduced can't be built.

The last known good one is 8e716c835f222d31ddcda39fc2a926f883b2d71e
The first known bad one is 5b3d66fd3c16708336b7d10beed9b0a0997a70d6

In between these commits are changes related to context managers, i.e. #460 and 39e64f9b0ac01a30d66c2f3df45ed6a040b06337

**Comment by skirpichev** [comment]
Thanks for bugreport.

Last mentioned commit seems to be related.  This works for me:
```diff
diff --git a/src/gmpy2_context.c b/src/gmpy2_context.c
index 8ef870be..5da26fd1 100644
--- a/src/gmpy2_context.c
+++ b/src/gmpy2_context.c
@@ -185,6 +185,7 @@ static PyObject *
 GMPy_CTXT_Exit(PyObject *self, PyObject *args)
 {
     int res = PyContextVar_Reset(current_context_var, ((CTXT_Object*)self)->token);
+    Py_DECREF(((CTXT_Object*)self)->token);
     if (res == -1) {
         SYSTEM_ERROR("Unexpected failure in restoring context.");
         return NULL;
```

I'll provide a pr.

**Comment by thomaswucher** [comment]
Thanks for looking into it this quickly. Your proposed fix works for me!
