### ISSUE TITLE
is_prime and is_probab_prime show wrong results

### ISSUE THREAD

**Issue by KhDenys** [aleaxit/gmpy#527]
I test this methods on primorial primes (look [here](https://en.wikipedia.org/wiki/Primorial_prime) and [here](https://oeis.org/A057704)) and almost always I have wrong results.
<img width="590" alt="image" src="https://github.com/user-attachments/assets/170e3697-6915-436e-b8c1-2d1713d8b1e5">

Sorry if I missed something

**Comment by skirpichev** [comment]
> Sorry if I missed something

You definitely miss source for your primorial() routine.

**Comment by KhDenys** [comment]
> > Sorry if I missed something
> 
> You definitely miss source for your primorial() routine.

Yeah, its implantation is n# and not p# 🫠
