### ISSUE TITLE
Can not temporarily change the current context settings

### ISSUE THREAD

**Issue by Shengyis** [aleaxit/gmpy#540]
As described in the Tutorial, the following code in the with statement should work with precision = 100 and outside with statement should work with precision = 53(default)
```
from gmpy2 import *
print(const_pi()) # should print 3.1415926535897931

with context(precision=100) as ctx:
  print(const_pi()) # should print 3.1415926535897932384626433832793
  ctx.precision += 20
  print(const_pi()) # should print 3.1415926535897932384626433832795028847

print(const_pi()) # should print 3.1415926535897931
```
However, it prints
```
3.1415926535897931
3.1415926535897932384626433832793
3.1415926535897932384626433832795028847
3.1415926535897932384626433832793
```
It seems 'with context(precision=100)' change the global context and in the with statement, +20 change the context temporarily.

I change the code and put precision = 100 inside with statement , result becomes reasonable. 
```
with context() as ctx:
  ctx.precision = 100
  print(const_pi()) # should print 3.1415926535897932384626433832793
  ctx.precision += 20
  print(const_pi()) # should print 3.1415926535897932384626433832795028847

print(const_pi()) # should print 3.1415926535897931
```

My gmpy2 version is 2.1.5 from conda-forge

**Comment by skirpichev** [comment]
> My gmpy2 version is 2.1.5 from conda-forge

Could you reproduce this with latest stable version (tutorial describes one)?  I don't think 2.1.x is maintained anymore.

**Comment by Shengyis** [comment]
> > My gmpy2 version is 2.1.5 from conda-forge
> 
> Could you reproduce this with latest stable version (tutorial describes one)? I don't think 2.1.x is maintained anymore.

Many thanks, I test it using gmpy2 2.2.1, the example in tutorial works. I have another question

```
from gmpy2 import *

a = mpfr('1')
b = mpfr('10')

ctxD = context(round=RoundDown)

print(ctxD.div(a, b)) # expect to print 0.099999999999999992
```
I create a context with RoundDown mode, and call the div method under this context, but I still get 0.10000000000000001 which is the default round to the nearest result. Many thanks!

**Comment by skirpichev** [comment]
Ah, that's a bug, thanks.  Context argument actually not passed.  Fill fix.
