### ISSUE TITLE
Search broken on docs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aleaxit/gmpy#73]
```
1. Browse to https://gmpy2.readthedocs.org/en/latest/
2. In the search box, search for 'isqrt'
3. No results.

Should find https://gmpy2.readthedocs.org/en/latest/mpz.html


```

Original issue reported on code.google.com by `matt.hickford` on 28 Apr 2013 at 4:25

**Comment by skirpichev** [comment]
@casevh, the https://gmpy2.readthedocs.org/en/latest/ - still not up to date, but this issue isn't relevant.
